<?php

$users = $this->users;

//print_r($teams);
//die(".");
?>
<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content">
                            <form id="frChamp_palpites" action="<?php echo $this->baseUrl('admin/index/adicionargranapost'); ?>" method="post">	
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                    <select id="usuario" name="usuario" class="form-control">
                                                    <?php   
                                                        if (empty($users)) {
                                                            echo '<option value="Vazio"></option>';    
                                                        }
                                                        
                                                        for ($i = 0; $i < count($users); $i = $i + 1) {
                                                            echo '<option '.$selected.' value="'.$users[$i]['us_username'].'">'.$users[$i]['us_username'].'</option>';
                                                        }                                                        
                                                    ?>
                                                    </select></div>
                                            </div>	
                                      </div>
                                    </div>  
                                    <div class="form-group">
                                      <div class="controls">
                                            <div class="input-group col-sm-4">
                                              <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                              <input type="text" id="valor" name="valor" class="form-control" placeholder="valor">
                                            </div>
                                      </div>
                                    </div>
                                
                                
                                
                            </form>   
                    </div>
            </div>
        </div>
    </div>