<?php

$users = $this->users;

//die(".");
?>

<div class="row">
        <div class="col-lg-12">
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Usuarios</h2>
                                <div class="box-icon">
                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table">
                                          <thead>
                                                  <tr>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th>
                                                         
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                          <?php
                                          
                                                for ($i = 0; $i < count($users); $i = $i + 1) { 
                                                    $user = $users[$i];
                                                    echo ' <tr>
                                                            <td>'.$user['us_id'].'</td>
                                                            <td>'.$user['us_username'].'</td>
                                                            <td>'.$user['us_email'].'</td>
                                                            <td>'.$user['us_dia_niver'].' - '.$user['us_mes_niver'].' - '.$user['us_anio_niver'].'</td>        
                                                            <td>'.$user['us_teamname'].'</td>
                                                            <td>'.$user['us_cash'].'</td>
                                                            </tr>    ';
                                                }

                                          ?>
                                                            
                                          </tbody>
                                 </table>  

                            <div class="form-actions">
                                
                            </div>

                        </div>
                </div>
        </div><!--/col-->

        <!--/col-->
</div>