<?php
    
    $matchs = $this->matchs;
   
$config = new Zend_Config_Ini("config.ini");
?>

<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content">
                            <form action="<?php echo $this->baseUrl('admin/jogos/jogospordata'); ?>" method="post">	
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                    <input type="text" name="mt_date_ini" placeholder="yyyy-mm-dd"/>                                                    
                                                    </div>
                                            </div>	
                                      </div>
                                    </div>    
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                    <input type="text" name="mt_date_fim" placeholder="yyyy-mm-dd"/>                                                    
                                                    </div>
                                            </div>	
                                      </div>
                                    </div>  
                                
                                <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <div class="controls">
                                                        <button type="submit" class="btn btn-info">Buscar</button>                                                   
                                                    </div>
                                            </div>	
                                      </div>
                                    </div>
                            </form>   
                    </div>
            </div>
        </div>
    </div>



<?php

 if (!empty($matchs)) {

?>


        
                <div class="box">
                        <div class="box-header">
                           
                            
                            
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Jogos</h2>
                                <div class="box-icon">

                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table" id="tb_palpites" >
                                          <thead>
                                                  <tr>
                                                    <th></th>
                                                    <th width="15%"></th>
                                                    <th></th>
                                                    <th width="15%"></th>
                                                    <th></th> 
                                                    <th width="15%"></th> 
                                                    <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              echo '<input type="hidden" value="'.count($matchs).'" name="count_palpites" id="count_palpites">';
                                              for ($i = 0; $i < count($matchs); $i = $i + 1) {  
                                                  
                                                    if (!$matchs[$i]['mt_played']) {
                                                        $matchs[$i]['mt_goal1'] = "";
                                                        $matchs[$i]['mt_goal2'] = "";
                                                    }
                                                  
                                                    $date = date("H:i",strtotime($matchs[$i]['mt_date']))."hs. ".date("d-m-y",strtotime($matchs[$i]['mt_date']) );
                                                    $matchs[$i]['mt_date'] = $date;
                                                    if (($i == 0) || ($i > 0 && strcmp($matchs[$i]['mt_date'],$matchs[$i-1]['mt_date']) != 0)) { 
                                                        echo '
                                                            <tr>
                                                                <td></td>
                                                                <td><b>Rodada '.$matchs[$i]['rd_round'].'</b></td>
                                                                <td><b>'.$date.'</b></td>
                                                                
                                                            </tr>';                                      
                                                    }
                                                        echo '
                                                            <tr id="tr_'.$i.'">
                                                                <td>'.$matchs[$i]['mt_id'].'</td>
                                                            <td width="15%">
                                                                <div class="input-group col-sm-7">
                                                                    <input disabled class="form-control" value="'.$matchs[$i]['mt_goal1'].'" type="text">
                                                                </div>
                                                            </td>
                                                            <td><img width="28px;" height="21px;" src="'.$config->host.$matchs[$i]['tm1_logo'].'" />'.$matchs[$i]['t1nome'].'</td>
                                                            <td></td>
                                                            <td><img width="28px;" height="21px;" src="'.$config->host.$matchs[$i]['tm2_logo'].'" />'.$matchs[$i]['t2nome'].'</td>
                                                            <td width="15%">     
                                                                <div class="input-group col-sm-7">		
                                                                    <input disabled class="form-control" value="'.$matchs[$i]['mt_goal2'].'" type="text">
                                                                </div>
                                                            </td>
                                                            <td>';
                                                                if ($matchs[$i]['mt_played'] == 0) {
                                                                    echo '<a href="'.$this->baseUrl("/admin/jogos/edit").'?jogo='.$matchs[$i]['mt_id'].'" class="btn btn-warning"><i class="fa fa-edit"></i></a>';                                                                    
                                                                }
                                                                
                                                            echo '</td>                                      
                                                        </tr>';
                                                    }
                                               
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                               
                            <div class="form-action">
                                <!--<a href="javascript:void(0)" id="btnAceitarPalpites" class="btn btn-success">Aceitar Palpites</a>--> 
                            </div>
                        </div>
                </div>



<?php
 }
?>
