<?php
    $teams1 = $this->team1;
//    print_r($teams1);
//    die(".");
    $teams2 = $this->team2;

?>

<div class="row">
				
				<div class="col-lg-12">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-edit"></i>Criar Penca</h2>
							<div class="box-icon">
								<a href="form-wizard.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
								<a href="form-wizard.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								<a href="form-wizard.html#" class="btn-close"><i class="fa fa-times"></i></a>
							</div>
						</div>
						<div class="box-content">
							
							<div class="step-content">
								<div class="step-pane active" id="step1">
								<form action="http://localhost/penca/public/register/addmatch" method="post">
                                                                    
                                                                    <?php
                                                                        
                                                                        for ($j = 0; $j < count(($teams1))/2; $j = $j + 1) {
                                                                            echo '                                                                        <div class="controls">
                                                                                <select id="tm_idchampionship" name="tm_idchampionship1'.$j.'" class="form-control">';
                                                                          
                                                                                        for ($i = 0; $i < count($teams1); $i = $i + 1) {
                                                                                            //print_r($teams[$i]["te"])
                                                                                            echo "<option value=".$teams1[$i]["tm_id"].">".$teams1[$i]["tm_name"]."</option>";
                                                                                        }
                                                                                        
                                                                                        
                                                                                    
                                                                                 
                                                                            echo ' </select>
                                                                        </div>';
                                                                            
                                                                            echo '                                                                        <div class="controls">
                                                                                <select id="tm_idchampionship" name="tm_idchampionship2'.$j.'" class="form-control">';
                                                                          
                                                                                        for ($i = 0; $i < count($teams1); $i = $i + 1) {
                                                                                            //print_r($teams[$i]["te"])
                                                                                            echo "<option value=".$teams1[$i]["tm_id"].">".$teams1[$i]["tm_name"]."</option>";
                                                                                        }
                                                                                        
                                                                                        
                                                                                    
                                                                                 
                                                                            echo ' </select>
                                                                        </div>';                                                                            
                                                                        }
                                                                    
                                                                    ?>
                                                                    
                                                              
                                                                    <div class="form-group">                                                                        
                                                                        <div class="controls">
                                                                                <select id="tm_idchampionship" name="tm_idchampionship" class="form-control">
                                                                                    <?php
                                                                                        for ($i = 0; $i < count($teams1); $i = $i + 1) {
                                                                                            //print_r($teams[$i]["te"])
                                                                                            echo "<option value=".$teams1[$i]["tm_id"].">".$teams1[$i]["tm_name"]."</option>";
                                                                                        }
                                                                                    
                                                                                    ?>
                                                                                </select>
                                                                        </div>
                                                                    </div>     
                                                                    
                                                                                                                                        <dd id="Registrar-element">
                                                                        <button name="Registrar" id="Registrar" type="submit" class="btn btn-success btn-next">Registrar</button>
                                                                    </dd>
                                                                </form>
                                                                    
                                                                    
								</div>
								
								
								
								

							</div>

						</div>

					</div>
					
				</div><!--/col-->

			</div>