<?php 

include APPLICATION_PATH.'/forms/penca.php';
include APPLICATION_PATH.'/decorators/Form.php';

$championships = $this->championships;

?>
<div class="row">
				
				<div class="col-lg-12">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-edit"></i>Criar Penca</h2>
							<div class="box-icon">
								<a href="form-wizard.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
								<a href="form-wizard.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								<a href="form-wizard.html#" class="btn-close"><i class="fa fa-times"></i></a>
							</div>
						</div>
						<div class="box-content">
							
							<div class="step-content">
								<div class="step-pane active" id="step1">
								<form action="http://localhost/penca/public/register/addpenca" method="post">
                                                                    <div class="form-group">
                                                                        <div class="controls">
                                                                            <div class="input-group"> 
                                                                                <span class="input-group-addon">
                                                                                    <i class="fa fa-pencil"></i>
                                                                                </span>
                                                                                <label for="pn_name"></label>
                                                                                <input id="pn_name" name="pn_name" class="form-control" placeholder="Nome da penca" type="" value="">
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <div class="controls">
                                                                            <div class="input-group"> 
                                                                                <span class="input-group-addon">
                                                                                    <i class="fa fa-users"></i>
                                                                                </span>
                                                                                <input id="pn_value" name="pn_value" class="form-control" placeholder="Quantidade maxima de participantes" type="" value="">
                                                                            </div>
                                                                        </div>
                                                                    </div>                                                                    
                                                                    <div class="form-group">
                                                                        <div class="controls">
                                                                            <div class="input-group"> 
                                                                                <span class="input-group-addon">
                                                                                    <i class="fa fa-dollar"></i>
                                                                                </span>
                                                                                <input id="pn_value" name="pn_value" class="form-control" placeholder="Valor" type="" value="">
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group">                                                                        
                                                                        <div class="controls">
                                                                                <select id="tm_idchampionship" name="tm_idchampionship" class="form-control">
                                                                                    <?php
                                                                                        for ($i = 0; $i < count($championships); $i = $i + 1) {
                                                                                            echo "<option value=".$championships[$i]["ch_id"].">".$championships[$i]["ch_nome"]."</option>";
                                                                                        }
                                                                                    
                                                                                    ?>
                                                                                </select>
                                                                        </div>
                                                                    </div>                       
                                                                    <div class="form-group">									
									<div class="controls">
									  <label class="checkbox">
										<input type="checkbox" id="pn_justfriends" name="pn_justfriends">
										Penca só para amigos
									  </label>
									</div>
                                                                    </div>     
                                                                    <div class="form-group">
                                                                        <div class="controls">
                                                                            <div class="input-group"> 
                                                                                <span class="input-group-addon">
                                                                                    <i class="fa fa-unlock-alt"></i>
                                                                                </span>
                                                                                <input id="pn_justfriends" name="pn_password" class="form-control" placeholder="Senha" type="" value="">
                                                                            </div>
                                                                        </div>
                                                                    </div>                                                                    
                                                                    <dt id="Registrar-label">&nbsp;</dt>
                                                                    <dd id="Registrar-element">
                                                                        <button name="Registrar" id="Registrar" type="submit" class="btn btn-success btn-next">Registrar</button>
                                                                    </dd>
                                                                </form>
                                                                    
                                                                    
								</div>
								
								
								
								

							</div>

						</div>

					</div>
					
				</div><!--/col-->

			</div>
    <div class="row">
    
<?php