<?php

    $matchs = $this->matchs;
    
//    print_r($matchs);
//    die(".");
?>
<div class="tab-pane active" id="palpites">
                                                    
    <div class="row">
        <form action="rodada_add" method="post" id="formPalpites">
        <div class="col-lg-10">
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Rodada: <?php echo $matchs[0]['mt_round']; ?></h2>
                                <div class="box-icon">
                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table">
                                          <thead>
                                                  <tr>
                                                          <th width="15%"></th>
                                                          <th></th>
                                                          <th width="40%">Data</th>
                                                          <th></th> 
                                                          <th width="15%"></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              echo '<input type="hidden" value="'.count($matchs).'" name="count_palpites">';
                                                for ($i = 0; $i < count($matchs); $i = $i + 1) {
                                                    echo '<input type="hidden" name="mt_'.$i.'" value="'.$matchs[$i]['mt_id'].'" />';
                                                    echo '<tr>
                                                            <td width="15%">
                                                                <div class="input-group col-sm-7">
                                                                    <input class="form-control"name="result1_'.$i.'" value="'.$matchs[$i]['mt_goal1'].'"  type="text" placeholder="0">
                                                                </div>
                                                            </td>
                                                            <td>'.$matchs[$i]['t1nome'].'</td>
                                                            <td width="40%">'.$matchs[$i]['mt_date'].'</td>
                                                            <td>'.$matchs[$i]['t2nome'].'</td>
                                                            <td width="15%">     
                                                                <div class="input-group col-sm-7">		
                                                                    <input class="form-control" value="'.$matchs[$i]['mt_goal2'].'" name="result2_'.$i.'" type="text" placeholder="0">
                                                                </div>
                                                            </td>
                                                            </td>                                      
                                                        </tr>';
                                                }
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                                 <div class="pagination pagination-centered">
                                  <ul class="pagination">
                                      
                                      <li><a href="table.html#">Prev</a></li>
                                        <li class="active">
                                          <a href="table.html#">1</a>
                                        </li>
                                        <li><a href="table.html#">2</a></li>
                                        <li><a href="table.html#">3</a></li>
                                        <li><a href="table.html#">4</a></li>
                                        <li><a href="table.html#">Next</a></li>
                                  </ul>
                                     
                                     <input type="submit" class="btn btn-success" value="Registrar Rodada" />
                                     
                                </div>     
                        </div>
                </div>
        </div>
        </form>
    </div>

</div>