<div class="container">
		<div class="row">
					<div id="content" class="col-sm-12 full">
			<div class="row">
				<div class="login-box">
					
					<div class="header">
						Login Bolão Craque de Bola
					</div>
					<p>
						<div class="fb-login-button" data-max-rows="1" data-size="xlarge" data-show-faces="false" data-auto-logout-link="false"></div>
					</p>
					
					<div class="text-with-hr">
						<span>ou nome de usuario</span>
					</div>
					
					<form class="form-horizontal login" action="<?php echo $this->baseUrl("/index/login"); ?>" method="post">
						
						<fieldset class="col-sm-12">
							<div class="form-group">
							  	<div class="controls row">
									<div class="input-group col-sm-12">	
										<input type="text" class="form-control" name="username" placeholder="Username or E-mail">
										<span class="input-group-addon"><i class="fa fa-user"></i></span>
									</div>	
							  	</div>
							</div>
							
							<div class="form-group">
							  	<div class="controls row">
									<div class="input-group col-sm-12">	
										<input type="password" class="form-control" name="password" placeholder="Password">
										<span class="input-group-addon"><i class="fa fa-key"></i></span>
									</div>	
							  	</div>
							</div>

							<div class="row">
							
								<button type="submit" class="btn btn-lg btn-primary col-xs-12">Login</button>
							
							</div>
								
						</fieldset>	

					</form>
					
					<a class="pull-left" href="page-login.html#">Esqueceu a senha?</a>
					<a class="pull-right" href="<?php echo $this->baseUrl()."/?register"; ?>">Cadastre-se!</a>
					
					<div class="clearfix"></div>				
						
				</div>
			</div><!--/row-->
		
		</div>	

			
			
				</div><!--/row-->		
		
	</div><!--/container-->