<?php
//include APPLICATION_PATH.'/decorators/Form.php';
    $em_acao = $this->em_acao;
    $points = $this->points;    
    $em_acao_group = $this->em_acao_group;

?>
<div class="row">
				
    <div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
            <div class="smallstat box">
                    <i class="fa fa-globe blue"></i>
                    <span class="title">Palpites em acao</span>
                    <span class="value"><?php echo $em_acao[0]['cantidad']; ?></span>
                    <a href="javascript:void(0)" id="emacao" class="more">
                        <span>Mais informacao</span>
                        <i class="fa fa-chevron-down"></i>
                    </a>
            </div>
    </div><!--/col-->
				
    <div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
            <div class="smallstat box">
                    <i class="fa fa-beer lightOrange"></i>
                    <span class="title">Puntuacao</span>
                    <span class="value"><?php
                        if (empty($points[0]['pontos'])) {
                            echo 0;
                        } else {
                            echo $points[0]['pontos'];
                        }
                    
                     ?></span>
                    <a href="javascript:void(0)" id="puntuacao" class="more">
                        <span>Mais informacao...</span>
                        <i class="fa fa-chevron-down"></i>
                    </a>
            </div>
    </div><!--/col-->
				
<!--    <div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
            <div class="smallstat box">
                    <i class="fa fa-dollar darkGreen"></i>
                    <span class="title">Caixa</span>
                    <span class="value">$1 999,99</span>
                    <a href="javascript:void(0)" id="caixa" class="more">
                        <span>Mais informacao...</span>
                        <i class="fa fa-chevron-down"></i>
                    </a>
            </div>
    </div>/col
				
    <div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
            <div class="smallstat box">
                    <i class="fa fa-moon-o lightBlue"></i>
                    <span class="title">Income</span>
                    <span class="value">$1 999,99</span>
                    <a href="" class="more">
                        <span>View More</span>
                        <i class="fa fa-chevron-down"></i>
                    </a>
            </div>
    </div>/col-->
			
</div>



<div class="col-md-13" id="box_emacao" style="display:none">
    <div class="box" id="box_box_emacao" carregado="no">
            <div class="box-header">
                <h2><i class="fa fa-th"></i><span class="break"></span>Palpites em acao...</h2>
                <div class="box-icon">
                        <a href="javascript:void(0)" id="fechar_emacao" class="btn-close"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <div class="box-content">
                   <?php echo $this->render('index/index/emacao.phtml'); ?>
            </div>
    </div>
</div>

<div class="col-md-13" id="box_puntuacao" style="display:none">
    <div class="box" id="box_box_puntuacao">
            <div class="box-header">
                <h2><i class="fa fa-th"></i><span class="break"></span>Puntuacao</h2>
                <div class="box-icon">
                        <a href="javascript:void(0)" id="fechar_puntuacao" class="btn-close"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <div class="box-content">
                   <?php echo $this->render('index/index/puntuacao.phtml'); ?>
            </div>
    </div>
</div>

<div class="col-md-13" id="box_caixa" style="display:none">
    <div class="box" id="box_box_caixa">
            <div class="box-header">
                <h2><i class="fa fa-th"></i><span class="break"></span>Caixa</h2>
                <div class="box-icon">
                        <a href="javascript:void(0)" id="fechar_caixa" class="btn-close"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <div class="box-content">
                   <?php echo $this->render('index/index/caixa.phtml'); ?>
            </div>
    </div>
</div>


<script type="text/javascript">
    
    function abrir_emacao() {
        $("#emacao").bind("click", function() {
            $("#box_emacao").attr("style","display:yes");
            $("#box_box_emacao").attr("style","display:yes");
            var ordenar = $("#ordenar").val();
            if ($("#box_box_emacao").attr("carregado") === 'no') {
                $("#box_box_emacao").attr("carregado","y");
                $.post("index/emacao", {ordem : ordenar}, function(response) {
                    for (var i = 0; i < response.length; i = i + 1) {
                        $("#tb_emacao").append('<tr>\n\
                        <td>'+response[i].ch_nome+'</td> \n\
                        <td width="15%">\n\
                            <div class="input-group col-sm-7">\n\
                                <input class="form-control" disabled="true" value="'+response[i].rs_res1+'" type="text" placeholder="0">\n\
                            </div>\n\
                        </td>\n\
                        <td>'+response[i].t1nome+'</td>\n\
                        <td></td>\n\
                        <td>'+response[i].t2nome+'</td>\n\
                        <td width="15%">\n\
                            <div class="input-group col-sm-7">\n\
                                <input class="form-control" disabled="true" value="'+response[i].rs_res2+'" type="text" placeholder="0"> \n\
                            </div>\n\
                        </td>  \n\
                        <td>\n\
                            Round '+response[i].mt_round+'\n\
                        </td>\n\\n\
                        <td>'+ response[i].mt_date +'</td>\n\
                    </tr>');
                    }
                    console.log(response);
                });
            }
        });
    }
    
    function fechar_emacao() {
        $("#fechar_emacao").bind("click", function() {
            $("#box_emacao").attr("style","display:none");
            abrir_emacao();           
        });
    }
    
    function abrir_caixa() {
        $("#caixa").bind("click", function() {
            $("#box_caixa").attr("style","display:yes");
            $("#box_box_caixa").attr("style","display:yes");
        });
    }
    
    function fechar_caixa() {
        $("#fechar_caixa").bind("click", function() {
            $("#box_caixa").attr("style","display:none");
            abrir_caixa();
        });
    }
    
    function abrir_puntuacao() {
       $("#puntuacao").bind("click", function() {
            $("#box_puntuacao").attr("style","display:yes");
            $("#box_box_puntuacao").attr("style","display:yes");
            
            $.post("index/puntuacao", function(response) {
                
                $("#td_acertados").html(response['ganados']);
                $("#td_errados").html(response['perdidos']);
                $("#td_puntuacao").html(response['pontos']);
                $("#td_position").html(response['pontos']);
                $('#td_global').html(response['position']);
                console.log(response);
           
            });
        });
    }
    
    function fechar_puntuacao() {
        $("#fechar_puntuacao").bind("click", function() {
            $("#box_emacao").attr("style","display:none");
            abrir_puntuacao();
        });
    }
    
    function trocar_ordem_emacao() {
        $("#ordenar").change(function() {
            $("#box_box_emacao").attr("carregado","no");
            $("#tb_emacao").html("");
            $("#emacao").click();            
        });
    }
    
    $(function() { 
        trocar_ordem_emacao();
        abrir_emacao();
        fechar_emacao();

        abrir_caixa();
        fechar_caixa();
        
        abrir_puntuacao();    
        fechar_puntuacao();
    });
    
    
    
</script>