<div class="row">
				
				<div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
					<div class="smallstat box">
						<i class="fa fa-bell blue"></i>
						<span class="title">Income</span>
						<span class="value">$1 999,99</span>
						<a href="" class="more">
							<span>View More</span>
							<i class="fa fa-chevron-right"></i>
						</a>
					</div>
				</div><!--/col-->
				
				<div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
					<div class="smallstat box">
						<i class="fa fa-cogs lightOrange"></i>
						<span class="title">Income</span>
						<span class="value">$1 999,99</span>
						<a href="" class="more">
							<span>View More</span>
							<i class="fa fa-chevron-right"></i>
						</a>
					</div>
				</div><!--/col-->
				
				<div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
					<div class="smallstat box">
						<i class="fa fa-laptop darkGreen"></i>
						<span class="title">Income</span>
						<span class="value">$1 999,99</span>
						<a href="" class="more">
							<span>View More</span>
							<i class="fa fa-chevron-right"></i>
						</a>
					</div>
				</div><!--/col-->
				
				<div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
					<div class="smallstat box">
						<i class="fa fa-moon-o lightBlue"></i>
						<span class="title">Income</span>
						<span class="value">$1 999,99</span>
						<a href="" class="more">
							<span>View More</span>
							<i class="fa fa-chevron-right"></i>
						</a>
					</div>
				</div><!--/col-->
			
			</div>



<div class="row">	
    <div class="col-lg-12">
            <div class="row">

<!--                    <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="box">
                                <?php echo $this->render('index/index/posiciones.phtml'); ?>								     
                            </div>
                    </div>/col-->
                    
                     <?php echo $this->render('index/index/pencas.phtml'); ?>

<!--                    <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="box span4" ontablet="span6" ondesktop="span4">
                                    <div class="box-header">
                                            <h2><i class="fa fa-user"></i>Ultimas Pencas</h2>
                                            <div class="box-icon">
                                                    <a href="widgets.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                                    <a href="widgets.html#" class="btn-close"><i class="fa fa-times"></i></a>
                                            </div>
                                    </div>
                                    <div class="box-content no-padding">
                                           								
                                    </div>
                            </div>
                    </div>/col-->
            </div><!--/row-->	
    </div><!--/col-->
</div>