<?php

    $pencas = $this->pencas;

//
//    print_r($pencas);
//    die(";");
    
?>

<div class="row">
				
				<div class="col-lg-12">
					
					<div class="row">
						
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="box">
								<div class="box-header">
									<h2><i class="fa fa-list"></i>Weekly Stat</h2>
									<div class="box-icon">
										<a href="widgets.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
										<a href="widgets.html#" class="btn-close"><i class="fa fa-times"></i></a>
									</div>
								</div>
								<div class="box-content">
									<ul class="dashboard-list">
										<li>
											<a href="widgets.html#">
												<i class="fa fa-arrow-up green"></i>                               
												<span class="green">92</span>
												New Comments                                    
											</a>
										</li>
									  <li>
										<a href="widgets.html#">
										  <i class="fa fa-arrow-down red"></i>
										  <span class="red">15</span>
										  New Registrations
										</a>
									  </li>
									  <li>
										<a href="widgets.html#">
										  <i class="fa fa-minus blue"></i>
										  <span class="blue">36</span>
										  New Articles                                    
										</a>
									  </li>
									  <li>
										<a href="widgets.html#">
										  <i class="fa fa-comment yellow"></i>
										  <span class="yellow">45</span>
										  User reviews                                    
										</a>
									  </li>
									  <li>
										<a href="widgets.html#">
										  <i class="fa fa-arrow-up green"></i>                               
										  <span class="green">112</span>
										  New Comments                                    
										</a>
									  </li>
									  <li>
										<a href="widgets.html#">
										  <i class="fa fa-arrow-down red"></i>
										  <span class="red">31</span>
										  New Registrations
										</a>
									  </li>
									  <li>
										<a href="widgets.html#">
										  <i class="fa fa-minus blue"></i>
										  <span class="blue">93</span>
										  New Articles                                    
										</a>
									  </li>
									  <li>
										<a href="widgets.html#">
										  <i class="fa fa-comment yellow"></i>
										  <span class="yellow">254</span>
										  User reviews                                    
										</a>
									  </li>
									</ul>
								</div>
							</div>
						</div><!--/col-->

						<div class="col-lg-6 col-md-6 col-sm-6">
							<div class="box span4" ontablet="span6" ondesktop="span4">
								<div class="box-header">
									<h2><i class="fa fa-user"></i>Last Users</h2>
									<div class="box-icon">
										<a href="widgets.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
										<a href="widgets.html#" class="btn-close"><i class="fa fa-times"></i></a>
									</div>
								</div>
								<div class="box-content no-padding">
									<ul class="users-list">

                                                                                    <?php
                                                                                    
                                                                                    for ($i = 0; $i < count($pencas); $i = $i + 1) {
                                                                                        echo '<li>
											<a href="widgets.html#">
												<img class="avatar" alt="Lucas" src="assets/img/avatar.jpg">
											</a>
                                                                                    
											<div class="name">'.$pencas[$i]['pn_name'].' 
												<div class="dropdown pull-right">
                                                                                                <span class="label label-success">this week</span>
												
													<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
														<li><a href="widgets.html#"><i class="fa fa-check"></i> Accept</a></li>
														<li><a href="widgets.html#"><i class="fa fa-times"></i>Reject</a></li>
														<li><a href="widgets.html#"><i class="fa fa-minus-sign-alt"></i>Block</a></li>
														<li><a href="widgets.html#"><i class="fa fa-trash"></i>Delete</a></li>
													</ul>
												</div>
											</div>
											<span class="place"><i class="fa fa-map-marker"></i>'.$pencas[$i]['ch_nome'].'</span>
											<span class="job"><i class="fa fa-briefcase"></i>Bolao: '.$pencas[$i]['pn_valueaccumulated'].'</span>                                 
                                                                                        
										</li>
                                                                                ';
                                                                                    }
                                                                                    ?>
                                                                                    
                                                        
									</ul>
								</div>
							</div>
						</div><!--/col-->
						
					</div><!--/row-->	
					
				</div><!--/col-->
				
				<!--/col-->
				
			</div>