
<form action="<?php echo $this->baseUrl("/index/registerteamsform"); ?>" method="post">
    <div class="form-group">
        <label class="control-label" for="textarea2">Textarea with Input Limits &amp; Autosizing</label>
        <div class="controls">
              <textarea id="teams" name="teams" rows="6" style="width: 100%; overflow: hidden; word-wrap: break-word; resize: horizontal; height: 126px;"></textarea>
        </div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>