<h2>1. INTRODUÇÃO</h2>
1.1 - O site do Bolão Craque de Bola é destinado a elaborar bolões para o Campeonato Brasileiro de Futebol, 
Campeonatos Estaduais e para as competições e Torneios oficiais que a Seleção Brasileira estiver 
envolvida. Para participar, é necessário fazer seu cadastro na plataforma para realizar seu palpite em um dos bolões disponíveis
por meio de acesso no menu "Palpites". Ao se cadastrar no seu primeiro bolão, o participante confirma estar de acordo com 
todos os itens abaixo mencionados. 

<br><br>

<h2>2. CADASTRO E OBRIGAÇÕES DO USUÁRIO</h2>
2.1 - A participação nos nossos bolões é paga sendo R$2,50 cada palpite do usuario para cada jogo, ficando R$2,00 para o bolão do jogo palpitado, R$ 0,25 taxa de serviço do site,
 R$ 0,13 para o bolão da rodada e R$ 0,12 para o bolão do campeonato.
<br>
2.2 - O cadastro nos bolões é feito acessando o menu Palpites na plataforma e escolhendo quantos palpites jogos deseja palpitar, finalizando o processo e pagamento na janela de "A confirmar" na mesma página.
<br>
2.3 - Não é necessário convite de bolão para participar dos bolões públicos e oficais do nosso site.
<br>
2.4 - É preciso prestar todas as informações solicitadas no cadastro para facilitar o contato da organização com os participantes e para o envio de e-mails. 
<br>
2.5 - NÃO é permitido a um usuário possuir mais de um cadastro no site. Caso você tenha esquecido sua senha, entre em contato com o administrador por intermédio do menu 
CONTATO ou utilize a ferramenta de recuperação de senha. O Administração se dá o direito de excluir um dos cadastros sem prévio aviso e cumprir os itens de punição previstos no item 5.15 do Regulamento.
<br>
2.6 - NÃO é permitido o uso de letras maiúsculas, emails, espaçamento e acentos nos logins e senhas de usuários.

<br><br>

<h2>3. PALPITES E PRAZOS</h2>
3.1 - Seus palpites poderão ser alterados quantas vezes você quiser até uma hora antes de cada jogo. Tome cuidado com o horário, pois caso você opte por deixar para dar seu 
palpite no último minuto, o site Bolão Craque de Bola não se responsabilizará por qualquer inconsistência no sistema que bloqueie os palpites antes do prazo previsto. Lembre-se que 
a internet é influenciada por diversos fatores que podem fazer com que o bloqueio ocorra alguns minutos antes ou depois.
<br>
3.2 - Todos os participantes receberão um e-mail com os palpites de todos os usuários após o fechamento dos prazos para palpites. Caso você não recebe, fique atendo na sua 
caixa de spam ou lixeira. Se for necessário, adicione os e-mails palpites@bolaocraquedebola.com.br e info@bolaocraquedebola.com.br na lista de excessões.
<br>
<br>

<h2>4. PONTUAÇÃO PADRÃO</h2>
4.1 - A pontuação dos bolões seguirá, por padrão, o seguinte sistema:
<br>
4.1.1 - Acerto em cheio do resultado: 5 pontos 
Jogo terminou Brasil 2x1 Argentina e participante apontou palpite de Brasil 2x1 Argentina, ou
Jogo terminou Brasil 2x2 Argentina e participante apontou palpite de Brasil 2x2 Argentina.
4.1.2 - Acerto do resultado do jogo: 1 ponto 
Jogo terminou Brasil 4x1 Argentina e participante apontou palpite de Brasil 3x0 Argentina, ou
Jogo terminou Brasil 4x1 Argentina e participante apontou palpite de Brasil 4x3 Argentina.
<br>
4.2 - Em jogos eliminatórios, será levado em consideração o resultado do jogo normal somados com a prorrogação, ou seja, o placar final após a prorrogação. 
<br>
4.3 - Os critérios de desempate são, respectivamente: Acertos em Cheio, Acerto do Ganhador.
<br>
4.4 - O critério de pontuação de um bolão específico poderá ser feito diferente. Fique atento ao regulamento específico de cada bolão.
<br>
4.5 - O ganhador do bolão do jogo é aquele que acertar somente o placar em cheio, somando tambem os pontos ganhando ao ranking geral e da rodada, onde quem pontuar
mais na rodada leva por pontos o bolão da rodada e quem estiver com mais pontos no ranking geral leva o bolão do campeonato.

<br>
<br>
<h2>5. REGRAS E CONDUTAS</h2>
5.1 - É proibido divulgar outros sites em mensagens e/ou foto de perfil.
<br>
5.2 - É proibido criar comentários com a maioria das palavras totalmente em maiúsculo (mensagem poderá ser deletada sem prévio aviso).<br>
5.3 - É proibido usar de expressões, palavras e frases que atinjam o site, seus participantes e administradores (palavras de baixo calão).<br>
5.4 - É proibido criar mensagens com endereços de arquivos infectados, o criador da mensagem poderá ser advertido ou tomar uma punição leve.<br>
5.5 - Evite erros gramaticais, os mesmos podem prejudicar a comunicação.<br>
5.6 - Antes de postar mensagens com algum link de arquivo, faça um scan online em sites como o vírus total (www.virustotal.com).<br>
5.7 - Tenha sempre em mente o que pode prejudicar ou beneficiar os usuários do site. Se tiver dúvidas quanto a isso peça ajuda ao administrador.<br>
5.8 - É proibido usar qualquer tipo de imagem pornográfica ou semi-pornográfica.<br>
5.9 - O Bolão Craque de Bola sugere usar sua foto pessoal como imagem de perfil.<br>
5.10 - É proibido o uso de imagens de susto e aberrações, sabendo que essas imagens podem trazer sérias consequências aos membros.<br>
5.11 - Opiniões, reclamações e dúvidas deverão ser encaminhadas por meio do menu CONTATO.<br>
5.12 - Evite mensagens que não tenham a ver com assuntos relacionados aos bolões do Bolão Craque de Bola.<br>
5.13 - Evite Gritos de Guerra com a maioria das palavras totalmente em maiúsculo (mensagem poderá ser editada sem prévio aviso).<br>
5.14 - Tudo que desrespeitar as regras que estão escritas nesta página pode ser um motivo para uma punição leve.<br>
5.15 - Existem 4 tipos de punições: Advertência, punição leve (bloqueio de acesso ao site por 1 semana), punição moderada e(bloqueio de acesso ao site por um mês) <br>
e punição severa (exclusão do usuário). O usuário receberá punições progressivamente de acordo com a reincidência de uma falha específica.<br>

<br>
<br>

<h2>6. RANKING E PRÊMIOS</h2>
6.1 - O Bolão Craque de Bola registrará os pontos de todos palpitadores que pontuarem após o final de cada jogo palpitado de cada bolão, realizado oficialmente pelo site,  A ideia visa estimular 
a saudável disputa entre nossos usuários pelas primeiras posições de cada bolão.
<br>
6.2 - O primeiro colocado do bolão da rodada ganhara o valor total ocumulado naquela rodada.
<br>
6.3 - Cada campeonato terá o bolão do campeonato tendo como vencedor quem pontuar mais no campeonato, a pontuação é obtida por palpites em jogos do campeonato, seguindo o item
4.1.1 e 4.1.2.
<br>
6.4 - O primeiro colocado do bolão do campeonato ganhara o valor total ocumulado do campeonato.
<br>
6.5 - O valor ganho caso o usuario vença o bolão seja ele um único jogo ou da rodada ou do campeonato, será entregue após 1 dia da finalização da partida ou rodada ou campeonato,
sendo adicionado o valor na conta do usuário vencedor.
<br>
6.6 - O usuário que estiver com saldo na conta acima do valor de R$25,00 poderá realizar uma solicitação por mês de retirada do valor solicitado, será cobrado uma taxa gerado pelo pagseguro.
 
<br><br>
<h2>7. BOLÕES</h2>
7.1 - O Bolão Craque de Bola disponibiliza os seguintes bolões: Bolão dos Estaduais com os principais jogos dos principais campeonatos estaduais de futebol, Bolão da Taça Libertadores 
com os jogos dos times brasileiros e todos os jogos da fase mata-mata, Bolão do Campeonato Brasileiro da 1ª Divisão com todos os jogos, Bolão de Copa do Mundo, Copa América e Eurocopa.
<br><br>
<h2>8. GERAL</h2>
8.1 O regulamento poderá sofrer alteração sem aviso prévio, informando o usuário após a alteração via pop-up ao logar na plataforma.