<?php

$config = new Zend_Config_Ini("config.ini");

?>

<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content" style="height:500px">
                        <div class="col-xs-7 col-sm-2">
                             <img class="profile-image col-xs-7 col-sm-12" src="<?php echo $config->host."/assets/img/resenhas/resenha1.png"; ?>" />
                             </div>
                    </div>
            </div>
        </div>
    </div>