<?php

$config = new Zend_Config_Ini("config.ini");

?>

<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content" style="height:500px">
                        <div style="text-align: center">
                            <h1>Bem-vindo a Bolao Craque de Bola</h1>
                            <br>
                            <h2>O que voce espera para palpitar?</h2>
                            <br>
                            
                        </div>
                        <div class="row">
                        <div class="col-xs-7 col-sm-3 col-sm-offset-5">
                             <img  style="outline: none;" class="profile-image" src="<?php echo $config->host."/assets/img/resenhas/resenha1.png"; ?>" />
                             </div>
                            </div>
                        
                        <div style="text-align: center">
                            <a href="<?php echo $this->baseUrl()."/penca/bolao"; ?>" class="btn btn-lg btn-primary btn-round">Palpitar</a>
                            <br><br>
                            
                        </div>
                    </div>
            </div>
        </div>
    </div>