<?php 
$championships = $this->championships;
?>

<form action="http://localhost/penca/public/register/addpenca" method="post">
    <div class="form-group">
        <div class="controls">
            <div class="input-group"> 
                <span class="input-group-addon">
                    <i class="fa fa-pencil"></i>
                </span>
                <label for="pn_name"></label>
                <input id="pn_name" name="pn_name" class="form-control" placeholder="Nome da penca" type="" value="">
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="controls">
            <div class="input-group"> 
                <span class="input-group-addon">
                    <i class="fa fa-users"></i>
                </span>
                <input id="pn_value" name="pn_value" class="form-control" placeholder="Quantidade maxima de participantes" type="" value="">
            </div>
        </div>
    </div>                                                                    
    <div class="form-group">
        <div class="controls">
            <div class="input-group"> 
                <span class="input-group-addon">
                    <i class="fa fa-dollar"></i>
                </span>
                <input id="pn_value" name="pn_value" class="form-control" placeholder="Valor" type="" value="">
            </div>
        </div>
    </div>
</form>