

<table class="table" id="">
        <thead>

                <tr>
                        <th width="15%"></th>
                        <th></th>
                </tr>
        </thead>   
        <tbody>
          <tr>    
              <td>Palpites jogados (3)</td> 
              <td width="15%">R$ 700,00</td>  
          </tr>   
          <tr>    
              <td>Palpites ganhados (3)</td> 
              <td width="15%">R$ 1000,00</td>  
          </tr>                                                                                                       


        </tbody>
</table>