

<table class="table" id="tb_palpites_feitos">
                                          <thead>
                                                      
                                                  <tr>
                                                          <th width="15%"></th>
                                                          <th></th>
                                                          <th width="15%"></th>
                                                          <th></th> 
                                                          <th width="15%"></th> 
                                                          <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              
                                                        
                                                            
                                                        
                                                            
                                                        
                                                            <input type="hidden" name="rs_3_input" id="rs_3" value="43">
                                                               
                                                            <tr name="rs_3_dados" pf="4" id="rstr2446">
                                                            <td>Brasileirao</td> 
                                                                <td width="15%">
                                                                <div class="input-group col-sm-7">
                                                                    <input class="form-control" disabled="true" name="p_result1_3" value="3" id="p_result1_3" type="text" placeholder="0">
                                                                </div>
                                                            </td>
                                                            <td id="team13">Grêmio</td>
                                                            <td></td>
                                                            <td id="team23">Corinthians</td>
                                                            <td width="15%">     
                                                                <div class="input-group col-sm-7">		
                                                                    <input class="form-control" disabled="true" name="p_result2_3" value="2" id="p_result2_3" type="text" placeholder="0">
                                                                </div>
                                                            </td>  
                                                            <td><button it="3" result="446" class="btn btn-danger excluir"><i class="fa fa-trash-o "></i></button><a it="3" result="446" class="btn btn-info editar"><i class="fa fa-edit"></i></a></td>
                                                        </tr><input style="display:none" type="hidden" name="rs_4_input" id="rs_4" value="44">
                                                        <tr name="rs_4_data" style="display:none" pf_d="5" id="rstr1-1">
                                                            <td></td>
                                                            <td id="date4">
                                                                <b>
                                                               01:00hs. 01-01-70
                                                                </b></td>                                      
                                                        </tr>

                                          </tbody>
                                 </table>