<div class="row">
    <div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
<form id="frChamp_palpites" action="../penca/meuspalpites" method="post">	
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                    <select id="ordenar" name="ordenar" class="form-control">
                                                    <option value="Vazio">Ordenar por:</option>
                                                    <option value="1">Campeonato</option>
                                                    <option value="2">Data</option>
                                                    <option value="3">Ronda</option>
                                                    </select></div>
                                            </div>	
                                      </div>
                                    </div>    
                            </form>
</div>
    
</div>
<table class="table" id="tb_palpites_feitos">
    <thead>

            <tr>
                    <th>Campeonato</th>
                    <th></th>
                    <th></th>
                    <th></th> 
                    <th></th> 
                    <th></th> 
                    <th>Ronda</th> 
                    <th>Data</th> 
            </tr>
    </thead>   
    <tbody id="tb_emacao">
            

    </tbody>
</table>
    