<?php

    $pencas = $this->pencas;

//
//    print_r($pencas);
//    die(";");
    
?>
<div class="box-header">
                                            <h2><i class="fa fa-list"></i>Weekly Stat</h2>
                                            <div class="box-icon">
                                                    <a href="widgets.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                                    <a href="widgets.html#" class="btn-close"><i class="fa fa-times"></i></a>
                                            </div>
                                    </div>
                                    <div class="box-content">
                                            <ul class="dashboard-list">
                                                    <li>
                                                            <a href="widgets.html#">
                                                                    <i class="fa fa-arrow-up green"></i>                               
                                                                    <span class="green">92</span>
                                                                    New Comments                                    
                                                            </a>
                                                    </li>
                                              <li>
                                                    <a href="widgets.html#">
                                                      <i class="fa fa-arrow-down red"></i>
                                                      <span class="red">15</span>
                                                      New Registrations
                                                    </a>
                                              </li>
                                              <li>
                                                    <a href="widgets.html#">
                                                      <i class="fa fa-minus blue"></i>
                                                      <span class="blue">36</span>
                                                      New Articles                                    
                                                    </a>
                                              </li>
                                              <li>
                                                    <a href="widgets.html#">
                                                      <i class="fa fa-comment yellow"></i>
                                                      <span class="yellow">45</span>
                                                      User reviews                                    
                                                    </a>
                                              </li>
                                              <li>
                                                    <a href="widgets.html#">
                                                      <i class="fa fa-arrow-up green"></i>                               
                                                      <span class="green">112</span>
                                                      New Comments                                    
                                                    </a>
                                              </li>
                                              <li>
                                                    <a href="widgets.html#">
                                                      <i class="fa fa-arrow-down red"></i>
                                                      <span class="red">31</span>
                                                      New Registrations
                                                    </a>
                                              </li>
                                              <li>
                                                    <a href="widgets.html#">
                                                      <i class="fa fa-minus blue"></i>
                                                      <span class="blue">93</span>
                                                      New Articles                                    
                                                    </a>
                                              </li>
                                              <li>
                                                    <a href="widgets.html#">
                                                      <i class="fa fa-comment yellow"></i>
                                                      <span class="yellow">254</span>
                                                      User reviews                                    
                                                    </a>
                                              </li>
                                            </ul>
                                    </div>