<?php
    $pencas = $this->pencas;

//
//    print_r($pencas);
//    die(";");
    
?>
<div class="box-header">
    <h2><i class="fa fa-list"></i>Mis posiciones</h2>
    <div class="box-icon">
            <a href="widgets.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
            <a href="widgets.html#" class="btn-close"><i class="fa fa-times"></i></a>
    </div>
</div>
<div class="box-content">
    <ul class="dashboard-list">
        <li>
                <a href="widgets.html#">
                        <i class="fa fa-arrow-up green"></i>                               
                        <span class="green">92</span>
                        New Comments                                    
                </a>
        </li>
    </ul>
</div>