

<table class="table" id="tb_palpites_feitos">
                                          <thead>
                                                      
                                                  <tr>
                                                          <th width="15%"></th>
                                                          <th></th>
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                            <tr>    
                                                <td>Puntuacao</td> 
                                                <td width="15%">1</td>  
                                            </tr>   
                                            <tr>    
                                                <td>Posicao global</td> 
                                                <td width="15%">2</td>  
                                            </tr>                                                                                                       
                                            <tr>
                                                <td>Palpites acertados...</td> 
                                                <td width="15%">3</td>                                           
                                            </tr>
                                            <tr>
                                                <td>Palpites errados...</td> 
                                                <td width="15%">4</td>                                           
                                            </tr>

                                          </tbody>
                                 </table>