<!--<div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
    <form  action="../penca/meuspalpites" method="post">	
            <div class="form-group">                                      
              <div class="controls">
                    <div class="input-group date col-sm-12">
                        <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                        <div class="controls">
                            <select id="sel_campeonato" name="sel_campeonato" class="form-control">
                                <option value="Vazio">Campeonato:</option>
                                <option value="1">Campeonato</option>
                                <option value="2">Data</option>
                                <option value="3">Ronda</option>
                            </select>
                        </div>
                    </div>	
              </div>
            </div>    
    </form>
</div>-->

<?php
   $user_id = $this->user_id;

?>

<table class="table" id="tb_palpites_feitos">
        <thead>

                <tr>
                        <th width="15%"></th>
                        <th></th>
                </tr>
        </thead>   
        <tbody>                                            

          <tr>    
              <td><a href="<?php echo $this->baseUrl("usuario/puntuacao?usuario=".$user_id); ?>" >Puntuacao</a></td> 
              <td width="15%" id="td_puntuacao">x</td>  
          </tr>   
          <tr>    
              <td><a href="<?php echo $this->baseUrl("usuario/posicaoglobal?usuario=".$user_id); ?>" >Posicao</a></td> 
              <td width="15%" id="td_global">x</td>  
          </tr>                                                                                                       
          <tr>
              <td><a href="<?php echo $this->baseUrl("usuario/acertados?usuario=".$user_id); ?>" >Acertos</a></td> 
              <td width="15%" id="td_acertados">x</td>                                           
          </tr>
          <tr>
              <td><a href="<?php echo $this->baseUrl("usuario/errados?usuario=".$user_id); ?>" >Erros</a></td> 
              <td width="15%" id="td_errados">x</td>                                           
          </tr>

        </tbody>
</table>