<?php

 $championship = $this->championships;
// $rodada = $this->rodada;
 $champ = $this->champ;

 $t = Zend_Registry::get('translate');   
 
 $config = new Zend_Config_Ini("config.ini");
 
?>

<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content">
                            <form id="frChamp" action="<?php echo $this->baseUrl()."/penca/bolao"; ?>" method="post">	
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                        <input type="hidden" value="<?php echo $champ; ?>" name="rodada" />
                                                    <select id="championship" name="champ" class="form-control">
                                                    <?php   
                                                        if (empty($pencas)) {
                                                            echo '<option value="Vazio"></option>';    
                                                        }
                                                        
                                                        for ($i = 0; $i < count($championship); $i = $i + 1) {
                                                            $selected="";
                                                            if ($champ == $championship[$i]['ch_id']) {
                                                                $selected = "selected";
                                                            }
                                                            echo '<option '.$selected.' value="'.$championship[$i]['ch_id'].'">'.$championship[$i]['ch_nome'].'</option>';
                                                        }                                                        
                                                    ?>
                                                    </select></div>
                                            </div>	
                                      </div>
                                    </div>    
                            </form>   
                    </div>
            </div>
        </div>
    </div>



<div class="row">
    <div class="col-lg-12">
        <?php echo $this->render('penca/bolao/paginacao.phtml'); ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-8">
        <div id="gif" style="display:none"><img class="col-sm-offset-5" width="100px" hight="100px" src="<?php echo $config->host."/assets/img/pendente.gif"; ?>" /></div>
        <div id="panel_palpites_palpites_feitos">
            <?php echo $this->render('penca/bolao/palpites_feitos.phtml'); ?>  

            <?php echo $this->render('penca/bolao/palpites.phtml'); ?>
                        
       </div>
    </div>
    
    <div class="col-lg-4">
        <?php echo $this->render('penca/bolao/posicoes.phtml'); ?>
    </div>
    
</div>

    <script type="text/javascript">
       $(function() {
           $("#championship").change(function() {
               $('#frChamp').submit();
             //  alert("TROCOU");
           })
       }); 
         
    </script>