
<?php

$champs = $this->champs;


?>


<div class="row">
        <div class="col-lg-12">
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-edit"></i>Criar Bolão</h2>

                        </div>
                        <div class="box-content">
                                <form class="form-horizontal" id="formcriarbolao" method="post" action="<?php echo $this->baseUrl("/penca/criarbolao"); ?>">	
                                          <div id="divnome" class="form-group">
                                                <div class="controls">
                                                  <input class="form-control focused" id="nome" name="nome" type="text" placeholder="Nome do Bolão">
                                                </div>
                                          </div>
                                          <div id="divvalor" class="form-group">
                                                <div class="controls">
                                                  <input class="form-control focused" id="valor" name="valor" type="number" placeholder="Valor ingresso (pode ser 0)">
                                                </div>
                                          </div>

                                          <div class="form-group">
                                                <label class="control-label" for="selectError3">Campeonato</label>
                                                <div class="controls">
                                                     <select name="champ" id="champ" class="form-control">
                                                    <?php
                                                        for ($i = 0; $i < count($champs); $i = $i + 1) {
                                                            echo '<option value="'.$champs[$i]['ch_id'].'">'.$champs[$i]['ch_nome'].'</option>';
                                                        }
                                                    ?>
                                                  </select>
                                                </div>
                                          </div>
                                          <div id="divprimer" class="form-group">
                                                <div class="controls">
                                                  <input class="form-control focused" id="primer" name="primer" type="number" placeholder="% primer lugar">
                                                </div>
                                          </div>
                                          <div id="divsegundo" class="form-group">
                                                <div class="controls">
                                                  <input class="form-control focused" id="segundo" name="segundo" type="number" placeholder="% segundo lugar">
                                                </div>
                                          </div>
                                          <div id="divtercer" class="form-group">
                                                <div class="controls">
                                                  <input class="form-control focused" id="tercer" name="tercer" type="number" placeholder="% tercer lugar">
                                                </div>
                                          </div>                                    
                                          <div class="form-actions">
                                                <a href="javascript:void(0);" id="btnCriarButton" class="btn btn-primary">Criar Bolão</a>
                                          </div>
                                  </form>

                        </div>
                </div>
        </div><!--/col-->

</div>


<script type="text/javascript"> 

$(function() {
   $('#btnCriarButton').bind('click', function() {
       var nome = $('#nome').val();
       var valor = $('#valor').val();
       var primer = $('#primer').val();
       var segundo = $('#segundo').val();
       var tercer = $('#tercer').val();
       var champ = $('#champ').val();
       
       var certo = true;
       
       if (nome == null || nome =='') {
           $("#divnome").addClass("has-error");
           $("#divnome").removeClass("has-success");
           certo = false;
           
       } else {
           $("#divnome").addClass("has-success");
           $("#divnome").removeClass("has-error");
       }
       
       if (valor == null || valor =='' || valor < 0) {
           $("#divvalor").addClass("has-error");
           $("#divvalor").removeClass("has-success");
           certo = false;
       } else {
           $("#divvalor").addClass("has-success");
           $("#divvalor").removeClass("has-error");
       }
       
       if (primer == null || primer =='' || primer < 0) {
           $("#divprimer").addClass("has-error");
           $("#divprimer").removeClass("has-success");
           certo = false;
       } else {
           $("#divprimer").addClass("has-success");
           $("#divprimer").removeClass("has-error");
       }     
       
       if (segundo == null || segundo =='' || segundo < 0) {
           $("#divsegundo").addClass("has-error");
           $("#divsegundo").removeClass("has-success");
           certo = false;
       } else {
           $("#divsegundo").addClass("has-success");
           $("#divsegundo").removeClass("has-error");
       }       
       
       if (tercer == null || tercer =='' || tercer < 0) {
           $("#divtercer").addClass("has-error");
           $("#divtercer").removeClass("has-success");
           certo = false;
       } else {
           $("#divtercer").addClass("has-success");
           $("#divtercer").removeClass("has-error");
       }           

       if (certo) {
           $("#formcriarbolao").submit();
       }
       
   }) ;
});

</script>