<?php

    $teams = $this->teams;
    $participantes = $this->participantes;
    $participantes = $participantes[0];

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];
?>

<div class="row profile">
				
				<div class="col-sm-3">
					
					<div class="row">
						<div class="col-xs-7 col-sm-12">
							<img class="profile-image" src="assets/img/gallery/photo9.jpg">
						</div>
						<div class="col-xs-5 col-sm-12">
							<h3>Informacao Geral</h3>

							<ul class="profile-details">
								<li>
									<div><i class="fa fa-briefcase"></i> Nome</div>
									<?php echo $info_penca['pn_name']; ?>
								</li>
								<li>
									<div><i class="fa fa-building-o"></i> Campeonato</div>
									<?php echo $info_penca['ch_nome']; ?>
								</li>
							</ul>		

							<h3>Usuarios</h3>

							<ul class="profile-details">
								<li>
									<div><i class="fa fa-phone"></i> Administrador</div>
									nome de usuario
								</li>
								<li>
									<div><i class="fa fa-tablet"></i>Disponibilidade</div>
									aberto
								</li>
								<li>
									<div><i class="fa fa-envelope"></i>Status</div>
									comecou
								</li>
							</ul>
						</div>	
					</div><!--/row-->	

				</div><!--/col-->
				
				<div class="col-sm-9">
					
					<ul class="nav nav-tabs" id="myTab">
					  	<li class="active"><a href="page-profile.html#skills">Skills</a></li>
					  	
					  	
					</ul>

					<div class="tab-content">
						<div class="tab-pane" id="skills">
							
							<div class="row">
								
								<div class="col-sm-5">
									<h2>About Me</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
									<h2>Bio</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
									<h2>Job</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
									<h2>Languages</h2>
									<div class="row">
										<div class="col-xs-4">
											<div style="width: 110px; height: 110px; line-height: 110px;" class="language-skill1 easyPieChart" data-percent="90"><span>90</span>%<canvas width="110" height="110"></canvas></div>
						                    <div style="text-align:center">English</div>
										</div><!--/col-->
										<div class="col-xs-4">
											<div style="width: 110px; height: 110px; line-height: 110px;" class="language-skill2 easyPieChart" data-percent="43"><span>43</span>%<canvas width="110" height="110"></canvas></div>
						                    <div style="text-align:center">Spanish</div>
										</div><!--/col-->
										<div class="col-xs-4">
											<div style="width: 110px; height: 110px; line-height: 110px;" class="language-skill3 easyPieChart" data-percent="17"><span>-16</span>%<canvas width="110" height="110"></canvas></div>
						                    <div style="text-align:center">German</div>
										</div><!--/col-->
									</div><!--/row-->
										
								</div><!--/col-->
								
								<div class="col-sm-7">
									<h2>My Skills</h2>
									<ul class="skill-bar">
							        	<li>
							            	<h5>Web Design</h5>
							            	<div class="meter"><span class="lightBlue" style="width: 40%;">40%</span></div>
							          	</li>
							          	<li>
							            	<h5>Wordpress</h5>
							            	<div class="meter"><span class="green" style="width: 80%;">80%</span></div>
							          	</li>
							          	<li>
							            	<h5>Branding</h5>
							            	<div class="meter"><span class="red" style="width: 100%;">100%</span></div>
							          	</li>
							          	<li>
							            	<h5>SEO Optmization</h5>
							            	<div class="meter"><span class="lightOrange" style="width: 60%;">60%</span></div>
							          	</li>
										
							      	</ul>
							
									<h2>Other Skills</h2>
									<canvas id="canvas" class="chartjs" height="450" width="450" style="width: 450px; height: 450px;"></canvas>
								</div><!--/col-->
									
							</div><!--/row-->		
							
						</div>
					  	<div class="tab-pane" id="friends">
							<ul class="friends-list clearfix">
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar.jpg"></a>
									<div>Lukasz Holeczek</div>
									<span class="label label-success">active</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar2.jpg"></a>
									<div>Ann Polansky</div>
									<span class="label label-warning">busy</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar3.jpg"></a>
									<div>May Lin</div>
									<span class="label label-important">blocked</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar4.jpg"></a>
									<div>Kate Norman</div>
									<span class="label label-default">offline</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar5.jpg"></a>
									<div>Mia Lopez</div>
									<span class="label label-important">blocked</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar6.jpg"></a>
									<div>Katia Svoboda</div>
									<span class="label label-success">active</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar7.jpg"></a>
									<div>Blanka Rosicky</div>
									<span class="label label-warning">busy</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar8.jpg"></a>
									<div>Garry Old</div>
									<span class="label label-success">active</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
								<li>
									<a class="avatar" href="page-profile.html#"><img src="assets/img/avatar9.jpg"></a>
									<div>Nick White</div>
									<span class="label label-success">active</span>
									<a href="page-profile.html#" class="fa fa-facebook-square"></a>
									<a href="page-profile.html#" class="fa fa-twitter-square"></a>
									<a href="page-profile.html#" class="fa fa-linkedin-square"></a>
								</li>
							</ul>	
						
					  	</div>
					  	<div class="tab-pane active" id="photos">
                                                    
                             <!-- swewrewr -->                       
                                        <div class="row">
				<div class="col-lg-6">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-align-justify"></i><span class="break"></span>Simple Table</h2>
							<div class="box-icon">
								<a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
								<a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								<a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
							</div>
						</div>
						<div class="box-content">
							<table class="table">
								  <thead>
									  <tr>
										  <th>Time</th>
										  <th>P</th>
										  <th>J</th>
										                                  
									  </tr>
								  </thead>   
								  <tbody>
                                                                      
                                                                   <?php   
                                                                   
                                                                        for ($i = 0; $i < count($teams); $i = $i + 1) {
                                                                   
                                                                            echo '<tr>
                                                                                    <td>'.$teams[$i]['tm_name'].'</td>
                                                                                    <td>'.$teams[$i]['tm_points'].'</td>
                                                                                    <td>Member</td>
                                                                                                                         
                                                                            </tr>';
                                                                        
                                                                        }
                                                                        
                                                                    ?>    
                                                                                                          
								  </tbody>
							 </table>  
							 <div class="pagination pagination-centered">
							  <ul class="pagination">
								<li><a href="table.html#">Prev</a></li>
								<li class="active">
								  <a href="table.html#">1</a>
								</li>
								<li><a href="table.html#">2</a></li>
								<li><a href="table.html#">3</a></li>
								<li><a href="table.html#">4</a></li>
								<li><a href="table.html#">Next</a></li>
							  </ul>
							</div>     
						</div>
					</div>
				</div><!--/col-->
				
				<!--/col-->
                                
                                
                                
                                <!-- PARTICIPANTES   -->
                                
                                <div class="col-lg-5 col-sm-6">
					<div class="smallchart blue box">
						<div class="title">Situacao</div>
						<div class="content"></div>
						<div class="value"></div>
					</div>
				</div>
                                
                                <div class="col-lg-5 col-sm-6">
					<div class="smallchart blue box">
						<div class="title">Participantes</div>
						<div class="content"><?php echo $participantes['participantes']; ?></div>
						<div class="value"></div>
					</div>
				</div>
                                
                                  <div class="col-lg-5 col-sm-6">
					<div class="smallchart blue box">
						<div class="title">Acumulado</div>
						<div class="content">R$ <?php echo $info_penca['pn_valueaccumulated']; ?></div>
						<div class="value"></div>
					</div>
				</div>
                                
			</div>     
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                          <!-- dfsdgsgfsf -->                          
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    <div class="row">	
				<div class="col-lg-12">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-align-justify"></i><span class="break"></span>Combined All Table</h2>
							<div class="box-icon">
								<a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
								<a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								<a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
							</div>
						</div>
						<div class="box-content">
							<table class="table table-bordered table-striped table-condensed">
								  <thead>
									  <tr>
										  <th>Username</th>
										  <th>Date registered</th>
										  <th>Role</th>
										  <th>Status</th>                                          
									  </tr>
								  </thead>   
								  <tbody>
									<tr>
										<td>Vishnu Serghei</td>
										<td>2012/01/01</td>
										<td>Member</td>
										<td>
											<span class="label label-success">Active</span>
										</td>                                       
									</tr>
									<tr>
										<td>Zbyněk Phoibos</td>
										<td>2012/02/01</td>
										<td>Staff</td>
										<td>
											<span class="label label-important">Banned</span>
										</td>                                       
									</tr>
									<tr>
										<td>Einar Randall</td>
										<td>2012/02/01</td>
										<td>Admin</td>
										<td>
											<span class="label label-default">Inactive</span>
										</td>                                        
									</tr>
									<tr>
										<td>Félix Troels</td>
										<td>2012/03/01</td>
										<td>Member</td>
										<td>
											<span class="label label-warning">Pending</span>
										</td>                                       
									</tr>
									<tr>
										<td>Aulus Agmundr</td>
										<td>2012/01/21</td>
										<td>Staff</td>
										<td>
											<span class="label label-success">Active</span>
										</td>                                        
									</tr>                                   
								  </tbody>
							 </table>  
							 <div class="pagination pagination-centered">
							  <ul class="pagination">
								<li><a href="table.html#">Prev</a></li>
								<li class="active">
								  <a href="table.html#">1</a>
								</li>
								<li><a href="table.html#">2</a></li>
								<li><a href="table.html#">3</a></li>
								<li><a href="table.html#">4</a></li>
								<li><a href="table.html#">Next</a></li>
							  </ul>
							</div>     
						</div>
					</div>
				</div><!--/col-->
			</div>  
							
					
					  	</div>
					</div>
					
				</div><!--/col-->	

			</div>