<?php

    $teams = $this->teams;
    $participantes = $this->participantes;
    $participantes = $participantes[0];

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];
    
    
?>
<input type="hidden" id="idpenca" value="<?php echo $info_penca['pn_id']; ?>" >


<div class="row profile">	
    <div class="col-sm-3">
        <div class="row">
            <div class="col-xs-7 col-sm-12">

            </div>
            <?php echo $this->render('penca/index/info_geral.phtml'); ?>
        </div>	
    </div>

    <div class="col-sm-9">

        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#principal">Principal</a></li>					  	
            <li class="" id="tbParticipantes"><a href="#participantes">Participantes</a></li>
            <li class="" id="tbPalpites"><a href="#palpites">Palpites</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane" id="palpites">
                <?php echo $this->render('penca/index/palpites.phtml');  ?>
            </div>            
            <div class="tab-pane" id="participantes">
                <?php echo $this->render('penca/index/participantes.phtml');  ?>
            </div>
            <div class="tab-pane active" id="principal">
                <?php echo $this->render('penca/index/principal.phtml');  ?>
            </div>
        </div>	

    </div>
</div>