<?php


    $champs = $this->championships;
    
    if (!empty($champs)) {
    
    $rondas = $this->rondas;
    $champ = $this->champ;
    
    $config = new Zend_Config_Ini("config.ini");
    $t = Zend_Registry::get('translate');    
    
?>
<input type="hidden" config="<?php echo $config->host; ?>" id="config_logo" />

<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content">
                            <form id="frChamp_palpites" action="<?php echo $this->baseUrl()."/penca/meuspalpites"; ?>" method="post">	
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                    <input type="hidden" value="1" name="rodada" />
                                                    <select id="championship" name="champ" class="form-control">
                                                    <?php   
                                                        if (empty($pencas)) {
                                                            echo '<option value="Vazio"></option>';    
                                                        }
                                                        
                                                        for ($i = 0; $i < count($champs); $i = $i + 1) {
                                                            $selected = "";
                                                            if (!empty($champ) && $champs[$i]['ch_id'] == $champ) {
                                                                $selected = "selected";    
                                                            }
                                                            echo '<option '.$selected.' value="'.$champs[$i]['ch_id'].'">'.$champs[$i]['ch_nome'].'</option>';
                                                        }                                                        
                                                    ?>
                                                    </select></div>
                                            </div>	
                                      </div>
                                    </div>    
                            </form>   
                    </div>
            </div>
        </div>
    </div>

<?php

    if (!empty($rondas)) {

          $teamuserid = $this->teamuserid;
          $teamusername = $this->teamusername;
          $palpites = $this->palpites;
          
//          print_r($palpites);
          
          
          if ($teamusername == "") {
              $teamusername = "Time do coracao";
          }
?>
<div class="box">
    <div class="box-content">
        <div class="pagination pagination-centered" style="margin: 0px !important">
            
            <ul class="pagination">
                    
                    <?php
//                    
//                        print_r($rodada);
//                        if ($rodada > 1) {
//                            echo '<li><a href="'.$this->baseUrl('/penca/bolao?rodada='.$rondas[$i-1]['mt_round'].'&champ='.$champ).'">Prev</a></li>';
//                        }
                  
                     ?>       
                  <?php
                        echo '<li><a id="teamusername" href="javascript:void(0)"><i class="fa fa-edit"></i></a></li><li><a href="'.$this->baseUrl('/penca/bolao?team='.$teamuserid.'&champ='.$champ).'" data-type="text" data-pk="1" data-original-title="Enter username" id="teamcoracao_nome" class="editable editable-click">'.$teamusername.'</a></li>';
                        for ($i = 0; $i < count($rondas); $i = $i + 1) {
                            $r = $i + 1;
                            $active = "";
                            if ($rondas[$i]['mt_round'] == $this->n_rodada ) { 
                                $active = 'class="active"';                                
                            } 
                            echo '<li '.$active.'><a href="'.$this->baseUrl('/penca/meuspalpites?rodada='.$rondas[$i]['mt_round'].'&champ='.$champ).'">'.$rondas[$i]['mt_round'].'</a></li>';
                        }

                  ?>    
                
                  <?php
//                    if (!empty($rondas[$i+1]['mt_round'])) {
//                        echo '<li><a href="'.$this->baseUrl('/penca/bolao?rodada='.$rondas[$i+1]['mt_round'].'&champ='.$champ).'">Next</a></li>';
//                    }
                          
                   ?>
            </ul>
        </div>
    
        <?php echo $this->render('componentes/timecoracao.phtml'); ?>
   
        
    </div>
</div>
<!--<div class="col-md-12">
    <div class="box">
            <div class="box-header">
                    <h2><i class="fa fa-th"></i><span class="break"></span><?php echo $t->_("palpites"); ?></h2>
            </div>
            <div class="box-content">
                    <div class="panel-group" id="accordion">
                        <?php

                            for ($i = 0; $i < count($rondas); $i = $i + 1) {
                                $round = $rondas[$i]['mt_round'];
                                echo '<input type="hidden" id="hd_ronda_'.$round.'" carregado="no">';                                
                                echo '<div class="panel panel-default champ" ronda="'.$round.'" champ="'.$champ.'">
                                    <div class="panel-heading">
                                      <h4 class="panel-title">
                                        <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="ui-elements.html#champ_'.$i.'">
                                          '.$t->_("rodada").' '.$round.'
                                        </a>
                                      </h4>
                                    </div>
                                    <div id="champ_'.$i.'" class="panel-collapse collapse" style="height: 0px;">
                                      <div class="panel-body">
                                          <table id="tb_'.$round.'">
                                              <tr>
                                                 <td>
                                                    <div id="gif_'.$round.'" style="display:none">
                                                        <img class="col-sm-offset-5" width="100px" hight="100px" src="'.$config->host."/assets/img/pendente.gif".'" />
                                                    </div>
                                                 </td>
                                              </tr>  
                                          </table>
                                      </div>
                                    </div>
                                  </div>';
                            }
                        ?>


                    </div>

            </div>
    </div>
</div>-->

<?php

   }
    
    }
    
    if (!empty($palpites)) {
    ?>



                <div class="box">
                    <div class="box-header">
                            <h2><i class="fa fa-align-justify"></i><span class="break"></span></h2>
                            <div class="box-icon">

                            </div>
                    </div>
                    <div class="box-content">
                        <div class="row">

                        <?php
                            $box = new Helpers_Box();
                            $box->matches = $palpites;
                            $box->base = $this->baseUrl();
                            $box->disabled_input = true;
                            $box->mas_info = false;
                            $box->show_final_result = true;
                            $box->palpites_goal = true;
                            $box->show_solo_nopalpitados = false;
                            $box->show_solo_palpitados = true;
                            $box->show_titulo_rodada = false;
                            $box->tamanho_box = "col-lg-3 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6";
                            $box->btn_excluir = true;
                            $box->btn_cantidad = false;
                            $box->id_result_input1 = "result1pf_";
                            $box->id_result_input2 = "result2pf_";
                            $box->id_box = "rs_dados_";
                            $box->ganadores = true;
//                            $box->infoescrita = true;
//                            $box->infoescrita_msg = "Encerrado";
//                            $box->btn_cantidad = true;
                            echo $box->box();

                        ?>


                        <div class="form-action">                              
                        </div>
                        </div>
                    </div>
                </div>
<?php

    }

?>



<script type="text/javascript">
    
    $(function() {
        $("#championship").change(function() {
            $('#frChamp_palpites').submit();
         });
    }); 
    
    $(function()  {
        
        
        ganadores_jogo();
        
        $("#teamusername").bind("click", function() {
            $("#teamcoracao_pick").show();    
        });
        
        $(".champ").bind("click",function() {
            var champ = $(this).attr("champ");
            var ronda = $(this).attr("ronda");
            var logo = $("#config_logo").attr("config");
            if ($("#hd_ronda_"+ronda).attr("carregado") === 'no') {
                $("#hd_ronda_"+ronda).attr("carregado","yes");
                $("#gif_"+ronda).attr("style", "display:block");
                $.post("getpalpites", {champ : champ, ronda : ronda}, function(response) {
                    for (var i = 0; i < response.length; i = i + 1) {

                        var button_excluir = "";
                        var icone_resultado = "";
                        
                        var resultado1 = "";
                        var resultado2 = "";
                        
                        if (response[i].rs_result == null) {
                            button_excluir = '<button class="btn btn-danger excluir"><i class="fa fa-trash-o "></i></button>';
                        } else {
                            if (response[i].rs_result === "0") {
                                icone_resultado = '';
                                resultado1 = '<span class="label label-danger">'+response[i].mt_goal1+'</span>';
                                resultado2 = '<span class="label label-danger">'+response[i].mt_goal2+'</span>';
                            } else {
                                resultado1 = '<span class="label label-success">'+response[i].mt_goal1+'</span>';
                                resultado2 = '<span class="label label-success">'+response[i].mt_goal2+'</span>';
                                icone_resultado = '<span  class="label label-success"><i class="fa fa-check"></i></span>';
                            }
                        }   

                        $("#tb_"+ronda).append('<tr>\n\
                                    <td width="15%" style="text-align:right">'+response[i].t1nome+'<img width="28px;" height="21px;" src="'+logo+response[i].tm1_logo+'" /></td>\n\
                                    <td width="2%" style="text-align:right">'+resultado1+'</td>\n\
                                    <td width="12%">\n\
                                        <div class="row">\n\
                                            <div class="col-xs-6 col-sm-6 col-lg-6">\n\
                                                <input type="text" disabled="true" value="'+response[i].rs_res1+'" class="form-control" />\n\
                                            </div>\n\
                                            <div class="col-xs-6 col-sm-6 col-lg-6">\n\
                                                <input type="text" disabled="true" value="'+response[i].rs_res2+'" class="form-control" />\n\
                                        </div>\n\
                                    </div></td>\n\
                                    <td width="2%">'+resultado2+'</td>\n\
                                    <td width="15%"><img width="28px;" height="21px;" src="'+logo+response[i].tm2_logo+'" />'+response[i].t2nome+'</td>\n\
                                    <td>'+button_excluir+'</td>\n\
                                    <td>'+response[i].mt_date+'</td>\n\
                                </tr>');
                    }
               
                    console.log(response);
                    $("#gif_"+ronda).attr("style", "display:none");
                });
            }

        });
    });
    
</script>