

<?php


$penca = $this->pencas;

$p_carregada = 0;

?>
<!-- var cela = '<table><tr name="rs_0_dados" pf="1" id="rstr2442">\n\
                                <td width="15%">\n\
                                    <div class="input-group col-sm-7">\n\
                                        <input class="form-control" disabled="true" name="p_result1_0" value="1" id="p_result1_0" type="text" placeholder="0">\n\
                                    </div>\n\
                                </td>\n\
                                <td id="team10">Atlético-MG</td>\n\
                                <td></td>\n\
                                <td id="team20">Palmeiras</td>\n\
                                <td width="15%">     \n\
                                    <div class="input-group col-sm-7">		\n\
                                    <input class="form-control" disabled="true" name="p_result2_0" value="2" id="p_result2_0" type="text" placeholder="0">\n\
                                    </div>\n\
                                </td>  \n\
                                <td>\n\
                                    <button it="0" result="442" class="btn btn-danger excluir"><i class="fa fa-trash-o "></i></button>\n\
                                    <a it="0" result="442" class="btn btn-info editar"><i class="fa fa-edit"></i></a>\n\
                                </td>\n\
                            </tr>\n\
                        </table>';-->

<input type="hidden" value="<?php echo $p_carregada; ?>" name="p_carregada">

<?php 
/*
for ($i = 0; $i < count($penca); $i = $i + 1) {

 echo '<div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
        <div class="smallstat box">
                
                <i class="'.$penca[$i]['pn_icone'].'"></i>
                <span class="change">'.$penca[$i]['ch_nome'].'</span><br>
                <span class="change">';
 
                    if (strlen($penca[$i]['ch_nome']) > 8) {
                        echo '<a href="'.$this->baseUrl('/penca/index/?penca=1').'">'.substr($penca[$i]['pn_name'],0,12).'...</a>';
                    } else {
                        echo $penca[$i]['pn_name'];
                    }

                echo '</span><br>';
                
                    if ($penca[$i]['pn_value'] > 0) {
                        echo '<span class="title"><i style="float:right;width:20px;font-wight:normal;font-size:16px;padding-top:0px;padding-bottom:0px;background: none;color:green;text-align:right" class="fa fa-dollar green"></i>R$ '.$penca[$i]['pn_value'].'</span><br>';
                    }
                    
                    if ($penca[$i]['pn_justfriends']) {
                        echo '<span class="title"><i style="float:right;width:20px;font-wight:normal;font-size:16px;padding-top:0px;padding-bottom:0px;background: none;color:red;text-align:right" class="fa fa-lock green"></i></span><br>';
                    }
                
                echo '';
                
                echo '<a href="" class="more">
                        <span>Mais informação...</span>
                        <i class="fa fa-angle-down"></i>
                </a>
        </div>
    </div>';

}

if ($p_carregada != 0) {
    $this->render('penca/penca/infopencasuperficial.phtml');
}

*/



$pencas = $this->pencas;

print_r($pencas);
?>



<div class="box">
                        <div class="box-header">
                            <h2><i class="fa fa-align-justify"></i><span class="break"></span>Bolões Disponiveis</h2></div><div class="box-content">
                    <div class="row">
                        
                        <?php
                        
                            for ($i = 0; $i < count($pencas); $i++) {
                        
                                ?>
                            
                        <div style="" id="760" class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6">
                        <div class="smallstat box"><table width="100%"><tbody><tr><td style="text-align:center"><b><a href="<?php echo $this->baseUrl("penca/pencabolao/?idpenca=".$pencas[$i]['pn_id']); ?>"><?php echo $pencas[$i]['pn_name']; ?></a></b></td>
                                    </tr></tbody></table><table width="100%">
                                        <tbody><tr><td style="text-align:center"><b>
            <?php echo $pencas[$i]['ch_nome']; ?></b>
                                                </td></tr>
                                        </tbody></table>
                            
                            <table width="100%"><tbody><tr><td style="text-align:center">Ingresso: R$<?php echo $pencas[$i]['pn_value'];  ?></td></tr></tbody></table>
                            <table width="100%"><tbody><tr><td style="text-align:center">Usuarios <?php echo $pencas[$i]['users'];  ?></td></tr></tbody></table>
                            
                          <div id="427" style="margin: 15px 0 0 0; ">
                              <a href="<?php echo $this->baseUrl("penca/convite/?participar=paticipar&idpenca=".$pencas[$i]['pn_id']); ?>"><span class="label label-success" style="margin-right:70px">Participar</span></a><span style="padding-right:10px" class="ac_760">R$ <?php echo $pencas[$i]['pn_valueaccumulated']; ?></span><div id="dvInfo_760" style="display:none"></div></div>    
                        </div>
                </div>
                        
                        <?php
                        
                            }
                        ?>
                        
                        <div class="form-action">                              
                    </div>
                    </div>
                </div>
        </div>