<?php

//    print_r($this->pencas);
//    die(".");


?>


<div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
        <div class="smallstat box">
                <i class="fa fa-bell blue"></i>
                <span class="title">Income</span>
                <span class="value">$1 999,99</span>
                <a href="" class="more">
                        <span>View More</span>
                        <i class="fa fa-chevron-right"></i>
                </a>
        </div>
</div>