<form action="selecionarbase" method="post">

        <div class="form-group">
            <div class="controls">
                <div class="input-group col-sm-2">
                    <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                    <input type="text" id="base" name="base" class="form-control" placeholder="Nome da base">
                </div>                                              
            </div>                          
        </div>                                        
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Trocar base</button>
        </div>
</form>