<form action="selecionarbase" method="post">

        <?php
            $config = new Zend_Config_Ini("config.ini");
        
        ?>
    
        <div class="form-group">
            <div class="controls">
                <div class="input-group col-sm-2">
                    <select name="base">
                        <option value="">Seleciona base</option>
                        <option value="<?php echo $config->baseteste; ?>">Teste</option>
                        <option value="<?php echo $config->baseproducao; ?>">Producao</option>                        
                    </select>
                    
                </div>                                              
            </div>                          
        </div>                                        
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Trocar base</button>
        </div>
</form>