<?php

    include APPLICATION_PATH."/helpers/html.php";

    $storage = new Zend_Auth_Storage_Session();
    $data = (get_object_vars($storage->read())); 

    $lostMaches = $this->lostMatches;
    $winMatches = $this->winMatches;
    $playedMatches = $this->playedMatches;
    $totalPoints = $this->totalPoints;

    $usuario = $this->usuario;
    
    $html = new Helpers_Html();
        
?>

<div class="row profile">
				
    <div class="col-sm-3">

            <div class="row">
                    <div class="col-xs-7 col-sm-12">
                        <form name="upload-form" id="upload-form" method="post" action="<?php ?>" enctype="multipart/form-data">
                            <img class="profile-image" src="assets/img/gallery/photo9.jpg">
                            <label class="btn btn-default btn-file">
                                Browse <input type="file" style="display: none;">
                                Submit <input type="submit" class="button">
                            </label>
                        </form>                            
                    </div>

            </div><!--/row-->	

    </div><!--/col-->

    <div class="col-sm-9">



            <div class="tab-content">
                    <div class="tab-pane active" id="skills">

                            <div class="row">

<div class="col-lg-12">
    
    <?php

    if ($data['us_id'] == $usuario) {
    
?>
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-edit"></i>Informacao de Usuario</h2>
							<div class="box-icon">
								
								<a href="form-elements.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								
							</div>
						</div>
						<div class="box-content">
							<form class="form-horizontal">
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-user"></i></span>
									  <input type="text" id="date" value="<?php echo $data['us_username']; ?>" disabled class="form-control">
									</div>
									
								  </div>
								</div>
								
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                                                          <input type="text" id="phone" value="<?php echo $data['us_cash']; ?>" disabled class="form-control">
									</div>
									
								  </div>
								</div>
								<div class="form-group">
<!--                                                                    <select id="championship" name="champ" class="form-control">
                                                                    <?php   
                                                                        if (empty($pencas)) {
                                                                            echo '<option value="Vazio"></option>';    
                                                                        }

                                                                        for ($i = 0; $i < count($championship); $i = $i + 1) {
                                                                            $selected="";
                                                                            if ($champ == $championship[$i]['ch_id']) {
                                                                                $selected = "selected";
                                                                            }
                                                                            echo '<option '.$selected.' value="'.$championship[$i]['ch_id'].'">'.$championship[$i]['ch_nome'].'</option>';
                                                                        }                                                        
                                                                    ?>
                                                                    </select>-->
								</div>
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
									  <input type="password" id="senha" class="form-control" placeholder="Senha">
									</div>
									
								  </div>
								</div>
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
									  <input type="password" id="novasenha" class="form-control" placeholder="Nova senha">
									</div>
									
								  </div>
								</div>
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
									  <input type="password" id="confirmacao" class="form-control" placeholder="Confirmacao">
									</div>
									
								  </div>
								</div>                                                            
								
								
								<div class="form-actions">
								  <button type="button" id="salvar_senha" class="btn btn-primary">Salvar</button>
								</div>
							</form>   

						</div>
					</div>
    
     <?php
                                
    }
                                
                                ?>
				</div>
                               
                               
                                
                                <div class="col-lg-12">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-edit"></i>Puntuacao</h2>
							<div class="box-icon">
								
								<a href="form-elements.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								
							</div>
						</div>
						<div class="box-content">
                                                    <?php echo $html->puntuacoes($totalPoints,0,$winMatches,$lostMaches,$playedMatches, $data['us_id'],$this->baseUrl()); ?>
 
						</div>
					</div>
				</div>
                            </div><!--/row-->		

                    </div>


            </div>

    </div><!--/col-->	

</div>

<script type="text/javascript">

    $(function() {
       $("#salvar_senha").bind("click", function() {
           var senha = $("#senha").val();
           
           var confirmacao = $("#confirmacao").val();
           
           var novasenha = $("#novasenha").val();
           if (novasenha === confirmacao && novasenha !== "" && confirmacao !== "") {
               $.post("usuario/salvarsenha", {senha : senha, novasenha : novasenha}, function(response) {
                    console.log(response);
                    if (response == 200) {                       
                        success_msg("Senha trocada com exito.");
                   } else {
                       info_msg("Nao successo");
                   }
               });
           } else {
               info_msg("Senha e confirmacao devem ser iguais e nao vazio.");
           }
       }); 
    });

</script>