<?php

//    include APPLICATION_PATH."/helpers/html.php";
    include APPLICATION_PATH."/forms/FotoPerfil.php";
    
    $storage = new Zend_Auth_Storage_Session();
    $data = (get_object_vars($storage->read())); 

    $lostMaches = $this->lostMatches;
    $winMatches = $this->winMatches;
    $playedMatches = $this->playedMatches;
    $totalPoints = $this->totalPoints;

    $usuario = $this->usuario;
    
    $html = new Helpers_Html();
     
    $f = new Forms_FotoPerfil();

    $config = new Zend_Config_Ini("config.ini");
    
//    $browserLocale = new Zend_Locale(Zend_Locale::BROWSER);
//    print_r($browserLocale);
//    die(",");
?>




<div class="row profile">
				
    <div class="col-sm-3">

            <div class="row">
                
                    <div class="box">
                    <div class="box-content">
                        <div class="col-xs-7 col-sm-12">
                            <img class="profile-image" src="<?php echo $config->host."/assets/img/usuarios/user.png"; ?>" />
<!--                            <?php echo $f; ?>                         -->
                        </div>                
                <div class="col-lg-12">						
							
                </div>
                <div class="box-content">
                    <?php echo $html->puntuacoes($totalPoints,0,$winMatches,$lostMaches,$playedMatches, $usuario,$this->baseUrl()); ?>
                </div>
					
				
                    </div>
            </div>

            </div><!--/row-->	

    </div><!--/col-->

    <div class="col-sm-9">



            <div class="tab-content">
                    <div class="tab-pane active" id="skills">

                            <div class="row">

<div class="col-lg-12">
    
    <?php

    if ($data['us_id'] == $usuario) {
    
?>
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-edit"></i>Informacao de Usuario</h2>
							<div class="box-icon">
								
								<a href="form-elements.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								
							</div>
						</div>
						<div class="box-content">
							<form class="form-horizontal">
                                                            
                                                            
                                                            
                                                            
								<div class="form-group">
                                                                    
                                                                    <?php
                                                                    
                                                                        $disabled = "disabled";
                                                                        $button = "";
//                                                                        print_r($data);
                                                                        if (!empty($data['us_idfacebook']) && $data['us_userbyfaceseted'] == 0) {
                                                                            $disabled = "";
                                                                            $button = '<button type="button" id="cadastrar_usuario" class="btn btn-success">Cadastrar Usuario</button>';
                                                                        }
                                                                    
                                                                        echo '<div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-user"></i></span>
									  <input type="text" id="username" value="'.$data['us_username'].'" '.$disabled.' class="form-control">'.$button.'
									</div>
									
								  </div>';
                                                                    
                                                                    ?>
								  
								  
								</div>
								
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                                                          <input type="text" id="phone" value="<?php echo $data['us_cash']; ?>" disabled class="form-control">
									</div>
									
								  </div>
								</div>
								<div class="form-group">
<!--                                                                    <select id="championship" name="champ" class="form-control">
                                                                    <?php   
                                                                        if (empty($pencas)) {
                                                                            echo '<option value="Vazio"></option>';    
                                                                        }

                                                                        for ($i = 0; $i < count($championship); $i = $i + 1) {
                                                                            $selected="";
                                                                            if ($champ == $championship[$i]['ch_id']) {
                                                                                $selected = "selected";
                                                                            }
                                                                            echo '<option '.$selected.' value="'.$championship[$i]['ch_id'].'">'.$championship[$i]['ch_nome'].'</option>';
                                                                        }                                                        
                                                                    ?>
                                                                    </select>-->
								</div>
                                                            <div id="gif" style="display:none"><img class="col-sm-offset-5" width="100px" hight="100px" src="<?php echo $config->host."/assets/img/pendente.gif"; ?>" /></div>
                                                            <div id="panel_senhas">
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
									  <input type="password" id="senha" class="form-control" placeholder="Senha">
									</div>
									
								  </div>
								</div>
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
									  <input type="password" id="novasenha" class="form-control" placeholder="Nova senha">
									</div>
									
								  </div>
								</div>
								<div class="form-group">
								  
								  <div class="controls">
									<div class="input-group col-sm-4">
									  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
									  <input type="password" id="confirmacao" class="form-control" placeholder="Confirmacao">
									</div>
									
								  </div>
								</div>   
                                                            
                                                           <div class="form-actions">
								  <button type="button" id="salvar_senha" class="btn btn-primary">Salvar</button>
								</div>
							</form>   

						</div>
					</div>
<!--    <div class="box">
						<div class="box-header">
							<h2><i class="fa fa-edit"></i>Opcoes de informacao</h2>
							<div class="box-icon">
								
								<a href="form-elements.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								
							</div>
						</div>
						<div class="box-content">
							<form class="form-horizontal">
                                                            <div class="controls">
                                                                <div class="input-group col-sm-4">
                                                                    <label class="switch switch-success">
                                                                        <?php
                                                                        
                                                                            $checked_palp = "";
                                                                            if ($data['us_palppublicos']) {
                                                                                $checked_palp = "checked";
                                                                            }
                                                                        
                                                                            echo '<input id="palpites_publicos" type="checkbox" class="switch-input" '.$checked_palp.'>';
                                                                                
                                                                        ?>
                                                                        <span class="switch-label" data-on="On" data-off="Off"></span>
                                                                        <span class="switch-handle"></span>
                                                                     </label>
                                                                    <span> Palpites públicos </span>
								</div>
                                                            </div>
                                                            
                                                             <div class="controls">
                                                                <div class="input-group col-sm-4">
                                                                    <label class="switch switch-success">
                                                                        
                                                                    <?php    
                                                                    
                                                                        $checked_punt="";
                                                                        if ($data['us_puntpublica']) {
                                                                            $checked_punt = "checked";
                                                                        }
                                                                        
                                                                        echo '<input id="puntuacao_publica" type="checkbox" class="switch-input" '.$checked_punt.'>';
                                                                                
                                                                    ?>            
									<span class="switch-label" data-on="On" data-off="Off"></span>
                                                                        <span class="switch-handle"></span>
                                                                    </label>
                                                                    <span> Puntuacao pública </span>
								</div>
                                                             </div>
								
                                                            <div class="form-actions">
								  <button type="button" id="salvar_opcoes" class="btn btn-primary">Salvar</button>
                                                            </div>
                                                        </form>
                                                </div>
    </div>-->
    
     <?php
                                
    }
                                
                                ?>
				</div>
                               
                               
                                
                                
                            </div><!--/row-->		

                    </div>


            </div>

    </div><!--/col-->	

</div>

<script type="text/javascript">

    $(function() {
       $("#cadastrar_usuario").bind("click", function() {
           var username = $("#username").val();
          $.post("usuario/cadastrarusuario", {username : username }, function(response) {
              if (response === 200) {
                  $("#username").attr("disabled","true");
                  $("#cadastrar_usuario").hide();
              }
          }); 
       }); 
        
       $("#salvar_opcoes").bind("click", function() {
           var palpites_publicos = $("#palpites_publicos").prop("checked");
           var puntuacao_publica = $("#puntuacao_publica").prop("checked");
           
           $.post("usuario/salvaropcoes", {palpitespublicos : palpites_publicos, puntuacaopublica : puntuacao_publica}, function(response) {
               console.log(response);
                if (200 == 200) {
                   success_msg("Opcoes alteradas com exito.");
               } else {
                   info_msg("Erro ao atualizar as opcoes.");
               }
           });
       }); 
        
        
       $("#salvar_senha").bind("click", function() {
           var senha = $("#senha").val();
           
           var confirmacao = $("#confirmacao").val();
           
           var novasenha = $("#novasenha").val();
           
           if (novasenha === confirmacao && novasenha !== "" && confirmacao !== "") {
               $("#panel_senhas").attr("style", "display:none");
               $("#gif").attr("style", "display:block");
               $.post("usuario/salvarsenha", {senha : senha, novasenha : novasenha}, function(response) {
                    console.log(response);
                    if (response == 200) {                       
                        success_msg("Senha trocada com exito.");
                   } else {
                       info_msg("Nao successo");
                   }
                   $("#panel_senhas").attr("style", "display:block");
                   $("#gif").attr("style", "display:none");
               });
           } else {
               if (senha !== "") {
                    info_msg("Senha e confirmacao devem ser iguais e nao vazio.");
                }
           }
       }); 
    });

</script>