<?php

//include APPLICATION_PATH."/helpers/html.php";
//$html = new Helpers_Html();

$matches = $this->matches;

//print_r($matches);

//echo $html->acertados($matches, $this->baseUrl());

$box = new Helpers_Box();
$box->disabled_input = true;
$box->mas_info = true;
$box->matches = $matches;
$box->palpites_goal = true;
$box->show_final_result = true;
$box->show_jugados = true;
$box->show_titulo_campeonato = true;
$box->show_titulo_rodada = true;
$box->tamanho_box = "col-lg-3 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6";
//$box->

echo $box->big_box();

?>

<script>
    $(function() {
       box_mais_info(); 
    });
    
    
</script>

