<?php

    $championship = $this->championships;
    $rondas = $this->rondas;
    $champ = $this->champ;
    
    $matchs = $this->rodadas;
    
    $config = new Zend_Config_Ini("config.ini");
    
    $t = Zend_Registry::get('translate'); 
    
//    print_r($rondas);

?>


<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content">
                            <form id="frChamp" action="<?php echo $this->baseUrl()."/campeonatos"; ?>" method="post">	
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                        <input type="hidden" value="<?php echo $champ; ?>" name="rodada" />
                                                    <select id="championship" name="champ" class="form-control">
                                                    <?php   
                                                        if (empty($pencas)) {
                                                            echo '<option value="Vazio"></option>';    
                                                        }
                                                        
                                                        for ($i = 0; $i < count($championship); $i = $i + 1) {
                                                            $selected="";
                                                            if ($champ == $championship[$i]['ch_id']) {
                                                                $selected = "selected";
                                                            }
                                                            echo '<option '.$selected.' value="'.$championship[$i]['ch_id'].'">'.$championship[$i]['ch_nome'].'</option>';
                                                        }                                                        
                                                    ?>
                                                    </select></div>
                                            </div>	
                                      </div>
                                    </div>    
                            </form>   
                    </div>
            </div>
        </div>
    </div>

<?php
            
      if (!empty($champ)) { 
          
          $teamuserid = $this->teamuserid;
          $teamusername = $this->teamusername;
          
          if ($teamusername == "") {
              $teamusername = "Time do coracao";
          }
?>

<!--<input type="hidden" value="<?php echo $champ ?>" id="champ">
<div class="box">
        <div class="box-content">-->
        
            <?php
            
                echo $this->render('componentes/paginacao.phtml');
            
            ?>
            
<!--        </div>
    </div>
</div>-->

<?php

    $teams_coracao = $this->teams;

?>



<div class="row">
    <div class="col-lg-8">
<?php

//print_r($matchs);
if (!empty($matchs)) {
                            $box = new Helpers_Box();
                            $box->matches = $matchs;
                            $box->base = $this->baseUrl();
                            $box->disabled_input = true;
                            $box->mas_info = false;
                            $box->show_final_result = true;
                            $box->palpites_goal = true;
                            $box->show_solo_nopalpitados = false;
                            $box->show_solo_palpitados = false;
                            $box->show_titulo_rodada = false;
                            $box->show_palpitar = true;
                            $box->tamanho_box = "col-lg-5 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6";
                            $box->btn_excluir = false;
                            $box->btn_cantidad = true;
                            $box->id_result_input1 = "result1pf_";
                            $box->id_result_input2 = "result2pf_";
                            $box->id_box = "rs_dados_";
                            $box->ganadores = true;
                            $box->titulo_bigbox = "Jogos";
//                            $box->infoescrita = true;
//                            $box->infoescrita_msg = "Encerrado";
//                            $box->btn_cantidad = true;
                            echo $box->big_box();

    }
?>
<div class="col-lg-6" style="padding-left:0px !important; padding-right:0px !important">
    <?php
    
        $ranking_round = new Helpers_Ranking();
        $rankings = $this->rankings;
        
        $ranking_round->vwranking = $rankings;
        $ranking_round->acumulado = isset($matchs[0]['rd_acumulado']) ? $matchs[0]['rd_acumulado'] : '0.00';
        $ranking_round->titulo=$t->_('ranking.rodada');
        $ranking_round->fechado = true;
        echo $ranking_round->ranking();
    
    ?>
    
</div>
        <div class="col-lg-6" style="padding-right:0px !important; padding-left:0px !important">        
            <?php 
            
                    $ranking_champ = new Helpers_Ranking();
                    $r_champ = $this->ranking_champ;
                    
                    $ranking_champ->vwranking = $r_champ;
                    $ranking_champ->acumulado = isset($r_champ[0]['ch_acumulado']) ? $r_champ[0]['ch_acumulado'] : '0.00';
                    $ranking_champ->titulo=$t->_("ranking.campeonato");;
                    $ranking_champ->fechado = true;
                    echo $ranking_champ->ranking();
            
            
            ?>
        </div>    
            
    </div>
   




<div class="col-lg-4">
        <?php echo $this->render('penca/bolao/posicoes.phtml'); ?>
    </div>

    </div>
    
<?php

      }
      
      ?>


<script type="text/javascript">
    $(function() {
        $("#championship").change(function() {
            $('#frChamp').submit();
         });
         
         box_mais_info(); 
    }); 
    
    
</script>