<?php

    $championship = $this->championships;
    $rondas = $this->rondas;
    $champ = $this->champ;
    
    $matchs = $this->rodadas;
    
    $config = new Zend_Config_Ini("config.ini");

?>


<div class="row">
    <div class="col-lg-12">
            <div class="box">
                    <div class="box-content">
                            <form id="frChamp" action="<?php echo $this->baseUrl()."/campeonatos"; ?>" method="post">	
                                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-12">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                        <input type="hidden" value="<?php echo $champ; ?>" name="rodada" />
                                                    <select id="championship" name="champ" class="form-control">
                                                    <?php   
                                                        if (empty($pencas)) {
                                                            echo '<option value="Vazio"></option>';    
                                                        }
                                                        
                                                        for ($i = 0; $i < count($championship); $i = $i + 1) {
                                                            $selected="";
                                                            if ($champ == $championship[$i]['ch_id']) {
                                                                $selected = "selected";
                                                            }
                                                            echo '<option '.$selected.' value="'.$championship[$i]['ch_id'].'">'.$championship[$i]['ch_nome'].'</option>';
                                                        }                                                        
                                                    ?>
                                                    </select></div>
                                            </div>	
                                      </div>
                                    </div>    
                            </form>   
                    </div>
            </div>
        </div>
    </div>

<?php
            
      if (!empty($champ)) { 
          
          $teamuserid = $this->teamuserid;
          $teamusername = $this->teamusername;
          
          if ($teamusername == "") {
              $teamusername = "Time do coracao";
          }
?>

<!--<input type="hidden" value="<?php echo $champ ?>" id="champ">
<div class="box">
        <div class="box-content">-->
        
            <?php
            
                echo $this->render('componentes/paginacao.phtml');
            
            ?>
            
<!--        </div>
    </div>
</div>-->

<?php

    $teams_coracao = $this->teams;

?>


<?php

 if (!empty($matchs)) {

//     print_r($matchs);
     
?>

<div class="row">
    <div class="col-lg-8">
<?php


        $box = new Helpers_Box();
        $box->disabled_input = true;
        $box->mas_info = true;
        $box->matches = $matchs;
        $box->palpites_goal = false;
        $box->show_final_result = false;
        $box->show_jugados = true;
        $box->show_titulo_campeonato = false;
        $box->show_titulo_rodada = false;
        $box->tamanho_box = "col-lg-6 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6";
        $box->big_box();
    }
?>

    </div>




<div class="col-lg-4">
        <?php echo $this->render('penca/bolao/posicoes.phtml'); ?>
    </div>

    </div>
    
<?php

      }
      
      ?>


<script type="text/javascript">
    $(function() {
        $("#championship").change(function() {
            $('#frChamp').submit();
         });
         
         box_mais_info(); 
    }); 
    
    
</script>