<?php

    $posicoes = $this->ranking;
//
//    print_r($posicoes);
//    die(".");
//    
    if (!empty($posicoes)) {
    
?>

<div class="col-lg-4">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-align-justify"></i><span class="break"></span>Ranking</h2>
							
						</div>
						<div class="box-content">
							<table class="table">
								  <thead>
									  <tr>                               
									  </tr>
								  </thead>   
								  <tbody>
                                                                      
                                                                   <?php   
                                                                   
                                                                        for ($i = 0; $i < count($posicoes); $i = $i + 1) {
                                                                   
                                                                            echo '<tr>
                                                                                    <td>'.($i+1).'</td>
                                                                                    <td>'.$posicoes[$i]['points'].'</td>
                                                                                    <td><a href="'.$this->baseUrl().'/usuario/index?usuario='.$posicoes[$i]['rk_iduser'].'">'.$posicoes[$i]['rk_username'].'</a></td>
                                                                                                                         
                                                                            </tr>';
                                                                        
                                                                        }
                                                                        
                                                                    ?>    
                                                                                                          
								  </tbody>
							 </table>  
							 <div class="pagination pagination-centered">
							  <ul class="pagination" id="ul_positions">

                                                                
                                                                
							  </ul>
							</div>     
						</div>
					</div>
    
    </div>
<?php

    };

?>