<?php

    $posicoes = $this->$ranking;

    if (!empty($posicoes)) {
    
?>


					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-align-justify"></i><span class="break"></span>Tabela de posicoes</h2>
							
						</div>
						<div class="box-content">
							<table class="table">
								  <thead>
									  <tr>
                                                                            <th>Pos</th>
                                                                            <th>Time</th>
                                                                            <th>P</th>
										                                  
									  </tr>
								  </thead>   
								  <tbody>
                                                                      
                                                                   <?php   
                                                                   
                                                                        for ($i = 0; $i < count($posicoes); $i = $i + 1) {
                                                                   
                                                                            echo '<tr>
                                                                                    <td id="tm_id'.$i.'">'.($i+1).'</td>
                                                                                    <td id="tm_name'.$i.'">'.$posicoes[$i]['points'].'</td>
                                                                                    <td id="tm_points'.$i.'">'.$posicoes[$i]['rk_username'].'</td>
                                                                                                                         
                                                                            </tr>';
                                                                        
                                                                        }
                                                                        
                                                                    ?>    
                                                                                                          
								  </tbody>
							 </table>  
							 <div class="pagination pagination-centered">
							  <ul class="pagination" id="ul_positions">

                                                                
                                                                
							  </ul>
							</div>     
						</div>
					</div>
<?php

    };

?>