<?php

$champs = $this->champs;
$champ = $this->champ;

?>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-content">
                <form id="frChamp_transactions" action="<?php echo $this->baseUrl()."/admin/transacoes"; ?>" method="post">	
                    <div class="form-group">                                      
                        <div class="controls">
                              <div class="input-group date col-sm-12">
                                      <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                      <div class="controls">
                                      <input type="hidden" value="1" name="rodada" />
                                      <select id="championship" name="championship" class="form-control">
                                      <?php   
                                          if (empty($pencas)) {
                                              echo '<option value="Vazio"></option>';    
                                          }

                                          for ($i = 0; $i < count($champs); $i = $i + 1) {
                                              $selected = "";
                                              if (!empty($champ) && $champs[$i]['ch_id'] == $champ) {
                                                  $selected = "selected";    
                                              }
                                              echo '<option '.$selected.' value="'.$champs[$i]['ch_id'].'">'.$champs[$i]['ch_nome'].'</option>';
                                          }                                                        
                                      ?>
                                      </select></div>
                              </div>	
                        </div>    
                    </div>                    
                </form>   
            </div>
        </div>
    </div>
</div>


<div class="box">
                    <div class="box-header">
                            <h2><i class="fa fa-align-justify"></i><span class="break"></span></h2>
                            <div class="box-icon">

                            </div>
                    </div>
                    <div class="box-content">
                        <div class="row">

                        <div style="" id="rs_dados_111" class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6">
                        <div class="smallstat box"><table width="100%"><tbody><tr><td style="text-align:center"><b>Domingo 11 Dec. 17:00hs</b></td></tr></tbody></table>
                            <table><tbody><tr>
            <td width="55%" style="text-align:left"><span id="69"><img width="28px;" height="21px;" src="http://localhost/penca/assets/img/logos/palmeiras.png"><a href="/penca/public/team/team?team=69&amp;champ=6">Palmeiras</a></span></td><td width="35%">
                <div class="row">
                <div class="col-xs-10 col-sm-10 col-lg-10 numeros">                    
                    <input id="result1pf_111" style="text-align:center" class="form-control numeros_input" disabled="" value="2" type="text">
                </div>
                </div>
            </td>
            </tr>
        </tbody></table>
                            <table><tbody><tr>
            <td width="55%" style="text-align:left"><span id="70"><img width="28px;" height="21px;" src="http://localhost/penca/assets/img/logos/flamengo.png"><a href="/penca/public/team/team?team=70&amp;champ=6">Flamengo</a></span></td><td width="35%">
                <div class="row">
                <div class="col-xs-10 col-sm-10 col-lg-10 numeros">                    
                    <input id="result2pf_111" style="text-align:center" class="form-control numeros_input" disabled="" value="1" type="text">
                </div>
                </div>
            </td>
            </tr>
        </tbody></table><div id="443" style="margin: 15px 0 0 0; "><span style="padding-right:10px" class="ac_111">2.00</span><button id="btn_excluir_111" title="Excluir palpite" data="2016-12-11 17:00:00" match="111" result="689" class="btn btn-xs btn-danger excluir"><i style="padding: 6px 0 !important; font-size: 10px !important; margin-right: 0px !important; width: 15px !important" class="fa fa-trash-o "></i></button><div id="dvInfo_111" style="display:none"></div></div>    
                        </div>
                </div>

                        <div class="form-action">                              
                        </div>
                        </div>
                    </div>
                </div>

<script type="text/javascript">
    
    $(function() {
       $("#championship").change(function() {
          $("#frChamp_transactions").submit();
          
       }); 
    });
    

</script>