<?php

$champs = $this->champs;
$champ = $this->champ;

?>
<form id="frChamp_transactions" action="<?php echo $this->baseUrl()."/admin/transacoes"; ?>" method="post">	
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-content">
                
                    <div class="form-group">                                      
                        <div class="controls">
                              <div class="input-group date col-sm-12">
                                      <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                      <div class="controls">
                                      <input type="hidden" value="<?php echo $champ; ?>" name="champ" />
                                      <select id="championship" name="championship" class="form-control">
                                      <?php   
                                          if (empty($pencas)) {
                                              echo '<option value="Vazio"></option>';    
                                          }

                                          for ($i = 0; $i < count($champs); $i = $i + 1) {
                                              $selected = "";
                                              if (!empty($champ) && $champs[$i]['ch_id'] == $champ) {
                                                  $selected = "selected";    
                                              }
                                              echo '<option '.$selected.' value="'.$champs[$i]['ch_id'].'">'.$champs[$i]['ch_nome'].'</option>';
                                          }                                                        
                                      ?>
                                      </select></div>
                              </div>	
                        </div>    
                    </div>                    
                 
            </div>
        </div>
    </div>
</div>

<?php

    $usuarios = $this->usuarios;
    $rondas = $this->rondas;
    
//    print_r($usuarios);
//    print_r($rondas);


?>


<div class="box">
                    <div class="box-header">
                            <h2><i class="fa fa-align-justify"></i><span class="break"></span></h2>
                            <div class="box-icon">

                            </div>
                    </div>
                    <div class="box-content">
                        <div class="row">

                            <div style="" id="rs_dados_111" class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12 col-xxs-12">
                                    <div class="form-inline" id="frFiltroTransacao" style="text-align:left !important;margin-bottom:15px">
                                        <div class="form-group">                                      
                                            <div class="controls">
                                                <div class="input-group">
                                                  <div class="controls">
                                                    <select id="rodada" name="rodada" class="form-control">
                                                    <option value="">Filtro por rodada</option>
                                                      <?php
                                                        $rodada = $this->rodada;
                                                        for ($i = 0; $i < count($rondas);$i = $i + 1) {
                                                            $selected = "";
                                                            if (!empty($rodada) && $rodada == $rondas[$i]["mt_round"]) {
                                                                $selected = "selected";
                                                            }
                                                            echo '<option '.$selected.' value="'.$rondas[$i]["mt_round"].'">'.$rondas[$i]["mt_round"].'</option>';
                                                        }
                                                      
                                                      ?>
                                                    </select>
                                                  </div>
                                                </div>                                        
                                            </div>    
                                        </div>
                                        
                                        <div class="form-group">                                      
                                            <div class="controls">
                                                <div class="input-group">
                                                  <div class="controls">
                                                        <select id="usuario" name="usuario" class="form-control">
                                                           <option value="">Filtro por usuario</option>
                                                            <?php
                                                                $usuario = $this->usuario;
                                                              for ($i = 0; $i < count($usuarios);$i = $i + 1) {
                                                                  $selected = "";
                                                                  if (!empty($usuario) && $usuario == $usuarios[$i]["us_id"]) {
                                                                      $selected = "selected";
                                                                  }
                                                                  echo '<option '.$selected.' value="'.$usuarios[$i]["us_id"].'">'.$usuarios[$i]["us_username"].'</option>';
                                                              }

                                                            ?>
                                                        </select>  
                                                  </div>
                                                </div>                                        
                                            </div>    
                                        </div>
                                        </div>
                                    
                                    
                                    
                                    <table class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12 col-xxs-12">
                                        <thead>
                                            <th width="10%">Data</th>
                                            <th width="10%">Transacao</th>
                                            <th width="10%">p/Campeonato</th>
                                            <th width="10%">p/Rodada</th>
                                            <th width="10%">p/Jogo</th>
                                            <th width="10%">Campeonato</th>
                                            <th width="10%">Rodada</th>
                                            <th width="10%">Jogo</th>
                                            <th width="10%">Usuario</th>
                                            <th width="10%">Cash</th>
                                            
                                        </thead>
                                        <tbody>
                                            
                                            <?php
                                                $tr = $this->transactions;
                                            
                                                for ($i = 0; $i < count($tr); $i = $i + 1) {                                            
                                                    echo '<tr>
                                                        <td width="10%">'.$tr[$i]['tr_date'].'</td>
                                                        <td width="10%">'.$tr[$i]['tr_valortransaccion'].'</td>
                                                        <td width="10%">'.$tr[$i]['tr_valorcampeonato'].'</td>
                                                        <td width="10%">'.$tr[$i]['tr_valorrodada'].'</td>
                                                        <td width="10%">'.$tr[$i]['tr_valorjogo'].'</td>
                                                            
                                                        <td width="10%">'.$tr[$i]['tr_res_ch_acumulado'].'</td>
                                                        <td width="10%">'.$tr[$i]['tr_res_rd_acumulado'].'</td>
                                                        <td width="10%">'.$tr[$i]['tr_res_mt_acumulado'].'</td>
                                                        <td width="10%">'.$tr[$i]['us_username'].'</td>
                                                        <td width="10%">'.$tr[$i]['tr_res_us_cash'].'</td>
                                                                
                                                    </tr>';
                                                }
                                                    
                                            ?>
                                        </tbody>
                                    </table>                                   
                            </div>

                        <div class="form-action">                              
                        </div>
                        </div>
                    </div>
                </div>
</form>
<script type="text/javascript">
    
    $(function() {
       $("#championship").change(function() {
          $("#frChamp_transactions").submit();
          
       }); 
       
       $("#rodada").change(function() {
           $("#frChamp_transactions").submit();
       });
       
       $("#usuario").change(function() {
           $("#frChamp_transactions").submit();
       });
    });
    

</script>