<div class="row">	
    <div class="col-lg-12">

                <div id="alert" class="alert alert-danger" style="display:none">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>Oh snap!</strong> Change a few things up and try submitting again.
                </div>
                <div id="success" class="alert alert-success" style="display:none">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>Sucesso!</strong><p id="sucesso_msg">You successfully read this important alert message.</p>
                </div>
                <div id="info" class="alert alert-info" style="display:none">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>Heads up!</strong> This alert needs your attention, but it's not super important.
                </div>
                <div id="warning" class="alert alert-warning" style="display:none">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <h4 class="alert-heading">Warning!</h4>
                        <p>Best check yo self, you're not looking too good. Nulla vitae elit libero, a pharetra augue. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
                </div>
    </div><!--/col-->
</div>