<?php

//    $storage = new Zend_Auth_Storage_Session();
//        $storage->clear();


$uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
//
//    print_r($uri);
//        die(".");
    
if (strpos($uri, 'public/?trocarsenha=')) {
    echo $this->render('trocarsenha.phtml');
}

else if (strpos($uri, 'public/?linkreferencia&userlinked=')) {
    echo $this->render('register.phtml');
}

 else if (strpos($uri, 'public/?register') !== false) {
   
    echo $this->render('register.phtml');    

} else if (strpos($uri, 'public/?login') !== false) {
    
    echo $this->render('login.phtml');    
    
} else if (strpos($uri,'public/?confmail=')) {
    
    echo "Processando...";
    
    
    $cod = Zend_Controller_Front::getInstance()->getRequest()->getParam('confmail');
    echo '<form action="index/confirmaremail" id="formConMail" method="post">'
    . '<input type="hidden" value="'.$cod.'" name="confmail"></form>';

    echo '<script type="text/javascript"> 
                window.onload=function(){
                    document.forms["formConMail"].submit();
                }
       </script>';
    //    echo $this->render('_head.php');
//    $cod = Zend_Controller_Front::getInstance()->getRequest()->getParam('confmail');
//    echo $c
//    $this->redirect("index/confirmaremail?confemail=".$cod);
}
else {
 
//        $storage = new Zend_Auth_Storage_Session();
//        $data = $storage->read();
        
        $storage = new Zend_Auth_Storage_Session();
//                print_r($data);
//        die(".");
        $data = "";
        if (!empty($storage)) {
            $x = $storage->read();
            if (!empty($x)) {
                $data = (get_object_vars($x));
            }
        }
//        print_r($data);
//        die(".");
        
        if (!empty($data) && !empty($data['us_codverificacion'])) {
            echo $this->render('_confirmemail.php');
        } else if (!empty($data) && $data['us_admin'] == 0) {
            echo $this->render('_head.php');      
        } else if (!empty($data) && $data['us_admin'] == 1) {           
            echo $this->render('_adminhead.php');      
        } else {
//            $config = new Zend_Config_Ini("config.ini");
            //$this->redirect()->toUrl($config->hostpublic);
            echo $this->render('login.phtml');            
        }
            
}