<?php

//    $storage = new Zend_Auth_Storage_Session();
//        $storage->clear();

$uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
//
//    print_r($uri);
//        die(".");

if (strpos($uri, 'public/?register') !== false) {
   
    echo $this->render('register.phtml');    

} else if (strpos($uri, 'public/?login') !== false) {
    
    echo $this->render('login.phtml');    
    
} else {
 
//        $storage = new Zend_Auth_Storage_Session();
//        $data = $storage->read();
        
        $storage = new Zend_Auth_Storage_Session();
//                print_r($data);
//        die(".");
        $data = "";
        if (!empty($storage->read())) {
            $data = (get_object_vars($storage->read()));
        }
//        print_r($data);
//        die(".");
        
        if (!empty($data) && $data['us_admin'] == 0) {
            echo $this->render('_head.php');      
        } else if (!empty($data) && $data['us_admin'] == 1) {
            echo $this->render('_adminhead.php');      
        } else {
            echo $this->render('login.phtml');            
        }
            
}