<?php

        $usuario = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');

?>  


<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>Bolão Craque de Bola</title>
	<meta name="description" content="Bolão Craque de Bola.">
	<meta name="author" content="Martin Dymenstein">
	<meta name="keyword" content="Bolão, Futebol, Brasileirão, Campeonato">
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
        <link href="<?php echo $this->baseUrl("assets/css/bootstrap.min.css"); ?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl("assets/css/style.min.css"); ?>"  rel="stylesheet">
	<link href="<?php echo $this->baseUrl("assets/css/retina.min.css"); ?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl("assets/css/print.css"); ?>" rel="stylesheet" type="text/css" media="print"/>
	<!-- end: CSS -->
	
   <?php echo $this->headScript()->appendFile($this->baseUrl('jquery/jquery-1.8.3.js')); ?>
   <?php echo $this->headScript()->appendFile($this->baseUrl('jquery/jquery-ui-1.9.2.custom.js')); ?>
   <?php echo $this->headScript()->appendFile($this->baseUrl('jquery/jquery-ui-1.9.2.custom.min.js')); ?> 
   <?php echo $this->headScript()->appendFile($this->baseUrl('assets/js/own.js')) ?>        
        
	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<script src="assets/js/respond.min.js"></script>
		
	<![endif]-->
            
	<!-- start: Favicon and Touch Icons -->
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="57x57" href="assets/ico/apple-touch-icon-57-precomposed.png">
	<link rel="shortcut icon" href="<?php echo $this->baseUrl().'assets/ico/icone.jpg'; ?>">
        <link rel="icon" href="assets/ico/icone.jpg">
	<!-- end: Favicon and Touch Icons -->	
		
</head>

<body>
	
   <div class="container">
		<div class="row">
				
			<!-- start: Main Menu -->
			
			<!-- end: Main Menu -->
						
			<!-- start: Content -->
			<div id="content" class="col-lg-12 col-sm-12 col-xs-12 ">
	<div class=" col-xs-12 col-sm-12 col-lg-6 col-lg-offset-4 callout" style="padding-top:20px">
                                <div class="box" style="background:white !important">
                                    <div class="header" style="color:white;background-color:#222; padding: 20px">
                                        <b>Cadastre-se Agora!</b>
					</div>
					<form id="novo_usuario" class="form-horizontal" role="form" action="public/index/registercompleted" style="padding: 40px 0 30px 30px">
                                            <div><span id="erro" style="display:none; color:red"></span></div>
                                                <input type="hidden" value="<?php echo $usuario; ?>" id="usuario">
                                                <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" style="width: 70%" id="nome" name="nome" placeholder="Nome completo">
						    </div>
						  </div>
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="email" class="form-control" style="width: 70%" id="email" name="email" placeholder="E-mail">
						    </div>
						  </div>
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" style="width: 40%" id="cpf" name="cpf" placeholder="CPF">
						    </div>
						  </div>
                                                  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" style="width: 30%" id="cep" name="cep" placeholder="CEP" >
						    </div>
						  </div>                                            
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Telefone">
						    </div>
						  </div>
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="password" class="form-control" id="senha" name="password" placeholder="Confirme a senha">
						    </div>
						  </div>                                                                                      
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <button type="button" id="btnCadastro" class="btn btn-success">Cadastra-se</button>
						    </div>
						  </div>                                               
					   </form>
                                    </div>
				</div>		
           
                            

<script type="text/javascript">

 
</script>
                            






    


<script type="text/javascript">

    $(function() {
       $("#btnCadastro").bind("click", function() {
           var nome = $("#nome").val();
           var email = $("#email").val();
           var cpf = $("#cpf").val();
           var senha = $("#senha").val();
           var cep = $("#cep").val();
           var telefone = $("#telefone").val();
           var usuario = $("#usuario").val();
           
           if (nome !== "" || email !== "" ) {
                    $.post("index/validacpf", {cpf : cpf}, function(response) {
                        if (response) {
                            
                            $.post("index/registercomplete", {usuario:usuario, nome : nome, email : email, cpf : cpf, senha : senha, cep : cep, telefone : telefone}, function(response) {

                                console.log(response);

                                if (!response) { 
                                    $("#erro").html("Erro ao realizar cadastro, verifique os dados.");
                                    $("#erro").show();                                        
                                } else  {
                                    var host = window.location.hostname;
                                    if (host === "localhost") {
                                        window.location = "http://localhost/penca/public";
                                    } else {
                                        window.location = "http://www.bolaocraquedebola.com.br/public";   
                                    }                                    
                                }
                                
                             });
                             
                        } else {
                            $("#erro").html("CPF incorrecto.");
                            $("#erro").show();
                        }
                    });
            } else {
                $("#erro").html("Erro ao realizar cadastro, verifique os dados.");
                $("#erro").show();
            }
       });
    });
    
    
    
</script>     
					
			</div>
			<!-- end: Content -->
				
				</div><!--/row-->		
		
	</div>
	
</body>