<?php

        $usuario = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');        
        $linked = Zend_Controller_Front::getInstance()->getRequest()->getParam('userlinked');

        $checked = "";
        if (!empty($linked)) {
            $checked = "checked";
        }
?>  


<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>Bolão Craque de Bola</title>
	<meta name="description" content="Bolão Craque de Bola.">
	<meta name="author" content="Martin Dymenstein">
	<meta name="keyword" content="Bolão, Futebol, Brasileirão, Campeonato">
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
        <link href="<?php echo $this->baseUrl("assets/css/bootstrap.min.css"); ?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl("assets/css/style.min.css"); ?>"  rel="stylesheet">
	<link href="<?php echo $this->baseUrl("assets/css/retina.min.css"); ?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl("assets/css/print.css"); ?>" rel="stylesheet" type="text/css" media="print"/>
	<!-- end: CSS -->
	
   <?php echo $this->headScript()->appendFile($this->baseUrl('jquery/jquery-1.8.3.js')); ?>
   <?php echo $this->headScript()->appendFile($this->baseUrl('jquery/jquery-ui-1.9.2.custom.js')); ?>
   <?php echo $this->headScript()->appendFile($this->baseUrl('jquery/jquery-ui-1.9.2.custom.min.js')); ?> 
   <?php echo $this->headScript()->appendFile($this->baseUrl('assets/js/own.js')) ?>        
        
	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<script src="assets/js/respond.min.js"></script>
		
	<![endif]-->
            
	<!-- start: Favicon and Touch Icons -->
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="57x57" href="assets/ico/apple-touch-icon-57-precomposed.png">
	<link rel="shortcut icon" href="<?php echo $this->baseUrl().'assets/ico/icone.png'; ?>">
        <link rel="icon" href="assets/ico/icone.png">
	<!-- end: Favicon and Touch Icons -->	
		
</head>

<body>
	
   <div class="container">
		<div class="row">
				
			<!-- start: Main Menu -->
			
			<!-- end: Main Menu -->
						
			<!-- start: Content -->
			<div id="content" class="col-lg-12 col-sm-12 col-xs-12 ">
	<div class=" col-xs-12 col-sm-12 col-lg-6 col-lg-offset-4 callout" style="padding-top:20px">
                                <div class="box" style="background:white !important">
                                    <div class="header" style="color:white;background-color:#222; padding: 20px">
                                        <b>Cadastre-se Agora!</b>
					</div>
					<form id="novo_usuario" class="form-horizontal" role="form" action="index/registercomplete" style="padding: 40px 0 30px 30px">
                                            <div><span id="erro" style="display:none; color:red"></span></div>
                                                <input type="hidden" value="<?php echo $usuario; ?>" name="usuario" id="usuario">
                                                <input type="hidden" value="<?php echo $linked; ?>" name="userlinked" id="userlinked">
                                                <input style="display:none" type="checkbox" id="isuserlinked" <?php echo $checked; ?> >
                                                <?php
                                                
                                                    if (!empty($linked)) { 
                                                        echo '<div class="form-group">
                                                            <div class="col-xs-12 col-sm-8 col-lg-8">
                                                                <input type="text" class="form-control" style="width: 70%" id="nomeusuario" name="nomeusuario" placeholder="Nome de usuario">
            						    </div>
                					</div>';
                                                        echo '<div class="form-group">
                                                            <div class="col-xs-12 col-sm-10 col-lg-10">
                                                                <input type="password" class="form-control" style="width: 70%" id="senha" name="senha" placeholder="Senha">
            						    </div>
                					</div>';                                                        
                                                    }
                                                
                                                ?>
                                                
                                                
                                                
						  <div class="form-group">
						    <div class="col-xs-12 col-sm-10 col-lg-10">
						      <input type="password" class="form-control" style="width: 70%" id="password" name="password" placeholder="Confirme a senha">
						    </div>
						  </div>   
                                                <br>
                                                
                                                <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" style="width: 70%" id="nome" name="nome" placeholder="Nome completo">
						    </div>
						  </div>
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="email" class="form-control" style="width: 70%" id="email" name="email" placeholder="E-mail">
						    </div>
						  </div>
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" style="width: 40%" id="cpf" name="cpf" placeholder="CPF">
						    </div>
						  </div>
                                                  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" style="width: 30%" id="cep" name="cep" placeholder="CEP" >
						    </div>
						  </div>                                            
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Telefone">
						    </div>
						  </div>    
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
                                                        <select id="dia" name="dia">
                                                            <option value="Vazio">Dia</option>
                                                            <?php
                                                                for ($i = 1; $i < 32; $i = $i + 1) {
                                                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                                                }                                                            
                                                            ?>
                                                        </select>
                                                        <select id="mes" name="mes">
                                                            <option value="Vazio">Mes</option>
                                                            <option value="1">Janeiro</option>
                                                            <option value="2">Fevreiro</option>
                                                            <option value="3">Marco</option>
                                                            <option value="4">Abril</option>
                                                            <option value="5">Maio</option>
                                                            <option value="6">Junho</option>
                                                            <option value="7">Julho</option>
                                                            <option value="8">Agosto</option>
                                                            <option value="9">Setembro</option>
                                                            <option value="10">Outubro</option>
                                                            <option value="11">Novembro</option>
                                                            <option value="12">Dezembro</option>
                                                            
                                                        </select>                                                        
                                                        <select id="ano" name="ano">
                                                            <option value="Vazio">Ano</option>
                                                            <?php
                                                                for ($i = 1998; $i > 1940; $i = $i - 1) {
                                                                    echo '<option value="'.$i.'">'.$i.'</option>';
                                                                }
                                                            
                                                            ?>
                                                        </select>                                                                 
						    </div>
						  </div> 
                                                <div class="form-group">
                                                    <div class="col-xs-10 col-sm-10 col-lg-10">
                                                        <div class="g-recaptcha" data-sitekey="6Lfs7QwUAAAAAGFKfDGDCXLku0ch8hBpDre3WUas"></div>
                                                    </div>
                                                </div>
						  <div class="form-group">
						    <div class="col-xs-10 col-sm-10 col-lg-10">
						      <button type="button" id="btnCadastro" class="btn btn-success">Cadastra-se</button>
						    </div>
						  </div>                                               
					   </form>
                                    </div>
				</div>		
           
                            

<script type="text/javascript">

 
</script>
                            






    


<script type="text/javascript">

    $(function() {
       $("#btnCadastro").bind("click", function() {
           var nome = $("#nome").val();
           var email = $("#email").val();
           var cpf = $("#cpf").val();
           var senha = $("#senha").val();
           var cep = $("#cep").val();
           var telefone = $("#telefone").val();
           var usuario = $("#usuario").val();
           var password = $("#password").val();
           var senha = $("#senha").val();
           
           var dia = $("#dia").val();
           var mes = $("#mes").val();
           var ano = $("#ano").val();
           
           var nomeusuario = $("#nomeusuario").val();
           
           var escomlinkreferencia = $("#isuserlinked").is(":checked");
           
           var tudocerto = true;
           if (escomlinkreferencia) {
               tudocerto = false;
               console.log("paso1");
               if (password === senha && password !== "" && senha !== "") {
               console.log("paso2");
               
                    $.post("index/usuarioexiste", {usuario : nomeusuario}, function(response) {
                        console.log("paso3"   );
                        if (!response) {
                            console.log("paso4");
                            tudocerto = true;
                            processamento(tudocerto);
                        } else {
                             $("#erro").html("Nome de usuario ja existe.");
                             $("#erro").show();
                        }
                    });
                } else {
                    $("#erro").html("Senha ou confirmacao incorretas");
                    $("#erro").show();
                }
           } else {
               processamento(tudocerto);
           }
           
           
           
           
       });
    });
    
    function processamento(tudocerto) {
        var nome = $("#nome").val();
        var email = $("#email").val();
        var cpf = $("#cpf").val();
        var senha = $("#senha").val();
        var cep = $("#cep").val();
        var telefone = $("#telefone").val();
        var usuario = $("#usuario").val();
        var password = $("#password").val();
        var senha = $("#senha").val();

        var dia = $("#dia").val();
        var mes = $("#mes").val();
        var ano = $("#ano").val();

        var nomeusuario = $("#nomeusuario").val();
        
//            console.log("paso5");
           if (tudocerto) {
                if (nome !== "" && email !== "") {
//                    console.log("paso6");
                 if (password !== "") {
//                    console.log("paso7");
                    if (dia !== "Vazio" && mes !== "Vazio" && ano !== "Vazio") {
//                        console.log("paso8");
                         $.post("index/validacpf", {cpf : cpf}, function(response) {
//                             console.log(response);
//                           console.log("paso9");
                             if (response) {
//                                console.log("paso10");
                                $.post("index/validaemail", { email : email }, function(response) {
//                                    console.log(response);
//                                    console.log("paso11");
                                    if (response) {
                                        $("#novo_usuario").submit();        
                                    } else {
                                        $("#erro").html("O e-mail ja esta cadastrado");
                                        $("#erro").show();                                        
                                    }
                                });
 
                             } else {
                                 
                                 $("#erro").html("CPF incorrecto.");
                                 $("#erro").show();
                                 
                             }
                             
                            });  

                         } else {
                             $("#erro").html("Verifique a data de aniversario.");
                             $("#erro").show();
                         }
                     } else {
                         $("#erro").html("Senha incorrecta.");
                         $("#erro").show(); 
                     }
                 } else {
                     $("#erro").html("Nome ou Email devem ser prenchidos.");
                     $("#erro").show();
                 }
            }
    }
    
</script>     

<script src='https://www.google.com/recaptcha/api.js'></script>

			</div>
			<!-- end: Content -->
				
				</div><!--/row-->		
		
	</div>
	
</body>
