<div class="box">
    <div class="box-content">
        <div class="pagination pagination-centered" style="margin: 0px !important">
            <ul class="pagination">
                  <li><a href="table.html#">Prev</a></li>
                  <li class="active">
                    <a href="table.html#">1</a>
                  </li>
                  <li><a href="table.html#">2</a></li>
                  <li><a href="table.html#">3</a></li>
                  <li><a href="table.html#">4</a></li>
                  <li><a href="table.html#">Next</a></li>
            </ul>
        </div>
    </div>
</div>