 <?php   

    $config = new Zend_Config_Ini("config.ini");
 
    $palpites = $this->results;
    
//    print_r($palpites);
    
    if (!empty($palpites)) {
        $rodada = $palpites[0]['mt_round'];   
    }
    
//    print_r(count($palpites));

//print_r($palpites);
//die(".");
    
if (!empty($palpites)) {

   $box = new Helpers_Box();
   $box->matches = $palpites;
   $box->base = $this->baseUrl();
   $box->disabled_input = true;
   $box->mas_info = false;
   $box->palpites_goal = true;
   $box->show_final_result = false;
   $box->show_solo_nopalpitados = false;
   $box->show_solo_palpitados = true;
   $box->show_titulo_rodada = false;
   $box->tamanho_box = "col-lg-5 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6";
   $box->btn_palpitar = false;
   $box->id_result_input1 = "result1p_";
   $box->id_result_input2 = "result2p_";
   $box->id_box = "fila_";
   $box->id_html_team = "teamp_";
 
    $box->big_box();
    
    
   ?>
        
                <div class="box">
                        <div class="box-header">
                            
                            <?php
                                    $titulo = "Palpites da Rodada: ".$palpites[0]['mt_round'];

                            ?>
                            
                            
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span><?php echo $titulo; ?></h2>
                                <div class="box-icon">
<!--                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>-->
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table" id="tb_palpites" >
                                          <thead>
                                                  <tr>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th> 
                                                          <th></th> 
                                                          <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              
                                              for ($i = 0; $i < count($palpites); $i = $i + 1) {
                                                  
                                                $st = 'style=""';
                                                
                                                    echo '<input '.$st.' type="hidden" name="rs_'.$i.'" id="rs_'.$i.'" value="'.$palpites[$i]['mt_id'].'" />';

                                                    if (($i == 0) || ($i > 0 && strcmp($palpites[$i]['mt_date'],$palpites[$i-1]['mt_date']) != 0)) { 
                                                        echo '<tr '.$st.' style="text-align:center" name="'.$palpites[$i]['mt_date'].'">
                                                                <td></td>
                                                                <td></td>
                                                                <td id="date'.$palpites[$i]['mt_id'].'"><b>'.  Helpers_Data::day($palpites[$i]['mt_date']).'</b></td>                                      
                                                        </tr>';
                                                                
                                                    } 
                                                            
                                                        echo '
                                                            <tr '.$st.' id="fila_'.$palpites[$i]['mt_id'].'">
                                                            <td style="text-align:right" id="team1p'.$palpites[$i]['mt_id'].'">'.Helpers_Html::getTeamLinkRight($this->baseUrl(), $palpites[$i]['tm1_id'], $palpites[$i]['t1nome'], $config->host.$palpites[$i]['tm1_logo'], $palpites[$i]['mt_idchampionship']).'</td>
                                                            <td></td>
                                                            <td class="col-sm-3 col-xs-3">
                                                                <div class="row">
                                                                    <div class="col-xs-6 col-sm-6 col-lg-6">
                                                                        <input style="text-align:center" class="form-control" value="'.$palpites[$i]['rs_res1'].'" disabled> 
                                                                    </div>
                                                                   <div class="col-xs-6 col-sm-6 col-lg-6">		
                                                                        <input style="text-align:center" class="form-control" value="'.$palpites[$i]['rs_res2'].'" disabled>
                                                                    </div>   
                                                                </div>
                                                            </td>   
                                                            <td></td>
                                                            <td style="text-align:left;" id="team2p'.$palpites[$i]['mt_id'].'">'.Helpers_Html::getTeamLinkLeft($this->baseUrl(),$palpites[$i]['tm2_id'], $palpites[$i]['t2nome'], $config->host.$palpites[$i]['tm2_logo'], $palpites[$i]['mt_idchampionship']).'</td>
                                                            <td><a href="'.$this->baseUrl("/usuario/index?usuario=".$palpites[$i]['us_id']).'" >'.$palpites[$i]['us_username'].'</a></td>                                      
                                                        </tr>';
                                                    }
                                               
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                               
                            <div class="form-action">
                                <!--<a href="javascript:void(0)" id="btnAceitarPalpites" class="btn btn-success">Aceitar Palpites</a>--> 
                            </div>
                        </div>
                </div>
       
<?php
}

?>

<script type="text/javascript">

    function submeter() {
         $(".palpite").bind('click', function() {
           var match = $(this).attr("match");
           var data = $(this).attr("data");

         //  alert("#result1p_" + it);
           var r1 = $("#result1p_" + match).attr("value");
           var r2 = $("#result2p_" + match).attr("value");
           var round = $("#round").val();
           var team1 = $("#team1p"+match).html();
           var team2 = $("#team2p"+match).html();

           if (parseInt(r1) >= 0 && parseInt(r2) >= 0 ) {
               $('#fila_'+match).attr("style","display:none");
                $.post("submeterpalpite",{ match : match, result1 : r1, result2 : r2, round : round  }, function(response) {
                    if (response.sucesso === 200) {
//                        console.log(response);
                        $('[name=rs_'+match+'_dados]').attr("style","display:yes");

                        $('[name="'+data+'"]').show();
    //                    $('[name=rs_'+match+'_data]').attr("style","display:yes");
    //
                        $('[name="p_result2_'+match+'"]').val(r2);
                        $('[name="p_result1_'+match+'"]').val(r1);

                        $("#sucesso_msg").html("Palpite adicionado: " + team1 + " " + response.rs_res1 + " - " + response.rs_res2 + " " + team2);
                        $("#append_success").html($("#success").html());
                        $(".alert-success").show();
                        fechar_sucesso();
                    } else {
                        $('#fila_'+match).attr("style","display:yes");
                    }
//                    excluir();
               });
           } else {
               $("#alert_msg").html("Ao inserir o palpite do jogo.");
               $("#append_danger").html($("#alert").html());
               $(".alert-danger").show();
               fechar_alert();
           }
        });
    }

    $(function() {
       submeter();
    });

</script>