<?php

$palpites_feitos = $this->palpites;
 
//print_r($palpites_feitos);


if (!empty($palpites_feitos)) {

   ?>

<input type="hidden" value="<?php echo $palpites_feitos[0]['mt_idchampionship']; ?>" name="champ" id="champ" />
<input type="hidden" value="<?php echo $palpites_feitos[0]['mt_round']; ?>" name="rodada" id="round" />


        
        <div class="col-lg-8" id="palpites_feitos">
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Rodada: <?php echo $palpites_feitos[0]['mt_round']; ?></h2>
                                <div class="box-icon">
<!--                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>-->
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table" id="tb_palpites_feitos">
                                          <thead>
                                                  <tr>
                                                          <th width="15%"></th>
                                                          <th></th>
                                                          <th width="15%"></th>
                                                          <th></th> 
                                                          <th width="15%"></th> 
                                                          <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              echo '<input cant="'.count($palpites_feitos).'" type="hidden" value="'.count($palpites_feitos).'" id="count_palpites_feitos" name="count_palpites_feitos">';
                                                for ($i = 0; $i < count($palpites_feitos); $i = $i + 1) {
                                                    echo '<input type="hidden" name="rs_'.$i.'" id="rs_'.$i.'" value="'.$palpites_feitos[$i]['mt_id'].'" />';
                                                    echo '
                                                        <tr pf_d="'.($i+1).'" id="rstr1'.$palpites_feitos[$i]['rs_id'].'">
                                                            <td></td>
                                                            <td id="date'.$i.'">
                                                                <b>
                                                               '.date("H:i",strtotime($palpites_feitos[$i]['mt_date']))."hs. ".date("d-m-y",strtotime($palpites_feitos[$i]['mt_date']) ).'
                                                                </b>';
                                                                
                                                                
                                                            echo '</td>                                      
                                                        </tr>
                                                            <tr pf="'.($i+1).'" id="rstr2'.$palpites_feitos[$i]['rs_id'].'">
                                                            <td width="15%">
                                                                <div class="input-group col-sm-7">
                                                                    <input class="form-control" disabled="true" name="p_result1_'.$i.'" value="'.$palpites_feitos[$i]['rs_res1'].'" id="p_result1_'.$i.'"  type="text" placeholder="0">
                                                                </div>
                                                            </td>
                                                            <td id="team1'.$i.'">'.$palpites_feitos[$i]['t1nome'].'</td>
                                                            <td></td>
                                                            <td id="team2'.$i.'">'.$palpites_feitos[$i]['t2nome'].'</td>
                                                            <td width="15%">     
                                                                <div class="input-group col-sm-7">		
                                                                    <input class="form-control" disabled="true" name="p_result2_'.$i.'" value="'.$palpites_feitos[$i]['rs_res2'].'" id="p_result2_'.$i.'" type="text" placeholder="0">
                                                                </div>
                                                            </td>  
                                                            <td>';
                                                            if (empty($palpites_feitos['rs_id'])) {
                                                                    echo '<button it="'.$i.'" result="'.$palpites_feitos[$i]['rs_id'].'"  class="btn btn-danger excluir">'
                                                                            . '<i class="fa fa-trash-o "></i></button>';
                                                                    echo '<a it="'.$i.'" result="'.$palpites_feitos[$i]['rs_id'].'" class="btn btn-info editar">'
                                                                            . '<i class="fa fa-edit"></i></button>';
//                                                                    echo '<button it="'.$i.'" match="'.$palpites_feitos[$i]['mt_id'].'" class="btn btn-xs btn-success palpite">Palpitar</button>';
                                                             }
                                                            echo '</td>
                                                        </tr>';
                                                }
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                               
                            <div class="form-action">
                                <!--<a href="javascript:void(0)" id="btnAceitarPalpites" class="btn btn-success">Aceitar Palpites</a>--> 
                            </div>
                        </div>
                </div>
            
            
<?php    
    echo '<div id="template_palpite_feito" style="display:none"><input type="hidden" name="rs_" id="rs_" value="" />';
    echo '<table id="tbresult">
        <tr id="rstr1">
            <td></td>
            <td id="date">
                <b></b>';
            echo '</td>                                      
        </tr>
            <tr id="rstr2">
            <td width="15%">
                <div class="input-group col-sm-7">
                    <input class="form-control" disabled="true" name="p_result1_" value="" id="p_result1_"  type="text" placeholder="0">
                </div>
            </td>
            <td id="team1"></td>
            <td></td>
            <td id="team2"></td>
            <td width="15%">     
                <div class="input-group col-sm-7">		
                    <input class="form-control" disabled="true" name="p_result2_" value="" id="p_result2_" type="text" placeholder="0">
                </div>
            </td>  
            <td>';
            echo '<button it="" result=""  class="btn btn-danger excluir"><i class="fa fa-trash-o "></i></button>';
            echo '<button it="" result="" class="btn btn-info editar"><i class="fa fa-edit"></i></button>';
            echo '</td>
        </tr></table></div>';
 ?>   
        </div>
<?php
}

?>




<script type="text/javascript">
    
    function excluir() {
        $(".excluir").bind('click', function() {
            var rs = $(this).attr("result");
 
          //  alert(rs);
            $.post("excluirpalpite",{ result : rs }, function(response) {
                $("#rstr1"+rs).html("");
                $("#rstr2"+rs).html("");
                var palpites = $("#count_palpites_feitos").attr("cant");
                var n_palpites = parseInt(palpites);
                if (palpites === '1') {
                    $("#palpites_feitos").html("");
                }
                n_palpites = n_palpites - 1;
                $("#count_palpites_feitos").attr("cant", n_palpites);
                $("#count_palpites_feitos").attr("value", n_palpites);
                console.log(response);
                
                $("#tbrodada tr").eq(1).attr("id","rstr"+n_palpites);
                $("#tbrodada tr").eq(1).find('td:eq(1)').attr("id","team1"+n_palpites.toString());                
                $("#tbrodada tr").eq(1).find('td:eq(3)').attr("id","team2"+n_palpites);
                $("#tbrodada tr").eq(1).find('td:eq(1)').html("A");
                $("#tbrodada tr").eq(1).find('td:eq(3)').html("B");
                
//                $("#tb_palpites tr").eq(1).find('td:eq(0)').find('input').attr("disabled",false);
//                $("#tb_palpites tr").eq(1).find('td:eq(0)').find('input').attr("value",r1);
//                $("#tb_palpites tr").eq(1).find('td:eq(0)').find('input').attr("disabled",true);
//                
//                $("#tb_palpites tr").eq(1).find('td:eq(4)').find('input').attr("disabled",false);
//                $("#tb_palpites tr").eq(1).find('td:eq(4)').find('input').attr("value",r2);
//                $("#tb_palpites tr").eq(1).find('td:eq(4)').find('input').attr("disabled",true);
                
                var date = $("date_").attr("value");
                
                $("#tbrodada tr").eq(1).find('td:eq(5)').find('button:eq(0)').attr("result",response);
                
                $("#tbrodada tr").eq(0).attr("id","rstr2"+response);
                $("#tbrodada tr").eq(1).attr("id","rstr1"+response);      
                
                $('#tb_palpites').append($("#tbrodada tbody").html());
                
                
            }); 
        });
    }
    
    $(function() { 
        excluir();
    });
    
    </script>