<?php

$palpites_feitos = $this->palpites;
 
//print_r($palpites_feitos);


if (!empty($palpites_feitos)) {

   ?>

<input type="hidden" value="<?php echo $palpites_feitos[0]['mt_idchampionship']; ?>" name="champ" id="champ" />
<input type="hidden" value="<?php echo $palpites_feitos[0]['mt_round']; ?>" name="rodada" id="round" />


        
       
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Rodada: <?php echo $palpites_feitos[0]['mt_round']; ?></h2>
                                <div class="box-icon">
<!--                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>-->
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table" id="tb_palpites_feitos">
                                          <thead>
                                                  <tr>
                                                          <th width="15%"></th>
                                                          <th></th>
                                                          <th width="15%"></th>
                                                          <th></th> 
                                                          <th width="15%"></th> 
                                                          <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              echo '<input cant="'.count($palpites_feitos).'" type="hidden" value="'.count($palpites_feitos).'" id="count_palpites_feitos" name="count_palpites_feitos">';
                                                for ($i = 0; $i < count($palpites_feitos); $i = $i + 1) {
                                                    $st = "";
                                                    if ($palpites_feitos[$i]['rs_id'] == -1) {
                                                        $st='style="display:none"';
                                                    }
                                                    echo '<input '.$st.' type="hidden" name="rs_'.$i.'_input" id="rs_'.$i.'" value="'.$palpites_feitos[$i]['mt_id'].'" />';
                                                    echo '
                                                        <tr name="rs_'.$i.'_data" '.$st.' pf_d="'.($i+1).'" id="rstr1'.$palpites_feitos[$i]['rs_id'].'">
                                                            <td></td>
                                                            <td id="date'.$i.'">
                                                                <b>
                                                               '.date("H:i",strtotime($palpites_feitos[$i]['mt_date']))."hs. ".date("d-m-y",strtotime($palpites_feitos[$i]['mt_date']) ).'
                                                                </b>';
                                                                
                                                                
                                                            echo '</td>                                      
                                                        </tr>
                                                            <tr name="rs_'.$i.'_dados" '.$st.' pf="'.($i+1).'" id="rstr2'.$palpites_feitos[$i]['rs_id'].'">
                                                            <td width="15%">
                                                                <div class="input-group col-sm-7">
                                                                    <input class="form-control" disabled="true" name="p_result1_'.$i.'" value="'.$palpites_feitos[$i]['rs_res1'].'" id="p_result1_'.$i.'"  type="text" placeholder="0">
                                                                </div>
                                                            </td>
                                                            <td id="team1'.$i.'">'.$palpites_feitos[$i]['t1nome'].'</td>
                                                            <td></td>
                                                            <td id="team2'.$i.'">'.$palpites_feitos[$i]['t2nome'].'</td>
                                                            <td width="15%">     
                                                                <div class="input-group col-sm-7">		
                                                                    <input class="form-control" disabled="true" name="p_result2_'.$i.'" value="'.$palpites_feitos[$i]['rs_res2'].'" id="p_result2_'.$i.'" type="text" placeholder="0">
                                                                </div>
                                                            </td>  
                                                            <td>';
                                                            if (empty($palpites_feitos['rs_id'])) {
                                                                    echo '<button it="'.$i.'" result="'.$palpites_feitos[$i]['rs_id'].'"  class="btn btn-danger excluir">'
                                                                            . '<i class="fa fa-trash-o "></i></button>';
                                                                    echo '<a it="'.$i.'" result="'.$palpites_feitos[$i]['rs_id'].'" class="btn btn-info editar">'
                                                                            . '<i class="fa fa-edit"></i></button>';
//                                                                    echo '<button it="'.$i.'" match="'.$palpites_feitos[$i]['mt_id'].'" class="btn btn-xs btn-success palpite">Palpitar</button>';
                                                             }
                                                            echo '</td>
                                                        </tr>';
                                                }
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                               
                            <div class="form-action">
                                <!--<a href="javascript:void(0)" id="btnAceitarPalpites" class="btn btn-success">Aceitar Palpites</a>--> 
                            </div>
                        </div>
                </div>
         
<?php
}

?>




<script type="text/javascript">
    
    function excluir() {
        $(".excluir").bind('click', function() {
            var rs = $(this).attr("result");
            var it = $(this).attr("it");
          //  alert(rs);
            $.post("excluirpalpite",{ result : rs }, function(response) {
               $("#info_msg").html("Palpite excluido!");
               $("#append_info").html($("#info").html());
               $(".alert-info").show();
                fechar_info();
                
                var count_palpites = $("#count_palpites").attr("value");
                var c_palpites = parseInt(count_palpites);// + 1;
//                $("#count_palpites").attr("value", c_palpites);
//                
//                $("#rstr1"+rs).html("");
//                $("#rstr2"+rs).html("");
//                var palpites = $("#count_palpites_feitos").attr("cant");
//                var n_palpites = parseInt(palpites);
//                if (palpites === '1') {
//                    $("#palpites_feitos").html("");
//                }
//                n_palpites = n_palpites - 1;
//                $("#count_palpites_feitos").attr("cant", n_palpites);
//                $("#count_palpites_feitos").attr("value", n_palpites);
//                console.log(response);
//                
//                $("#tbrodada tr").eq(1).attr("id","rstr"+n_palpites);
//                $("#tbrodada tr").eq(1).find('td:eq(1)').attr("id","team1"+n_palpites.toString());                
//                $("#tbrodada tr").eq(1).find('td:eq(3)').attr("id","team2"+n_palpites);
//                $("#tbrodada tr").eq(1).find('td:eq(1)').html(response[0].t1nome);
//                $("#tbrodada tr").eq(1).find('td:eq(3)').html(response[0].t2nome);
//                
//                var date = $("date_").attr("value");
//                
//                $("#tbrodada tr").eq(1).find('td:eq(5)').find('button:eq(0)').attr("result",response);
//                
//                $("#tbrodada tr").eq(1).attr("id","trp_"+c_palpites);
//                //$("#tbrodada tr").eq(1).attr("id","rstr1"+response);      
//                
//                $('#tb_palpites').append($("#tbrodada tbody").html());
                
                console.log(response);
                
                $('[name=rs_'+it+'_dados]').attr("style","display:none");
                $('[name=rs_'+it+'_input]').attr("style","display:none");
                $('[name=rs_'+it+'_data]').attr("style","display:none");  
                
                $('#trp_'+it).attr("style", "display:yes");
                
                submeter();
            }); 
        });
    }
    
    $(function() { 
        excluir();
    });
    
    </script>