<?php

    $config = new Zend_Config_Ini('config.ini');

    $teams = $this->teams;
    $champ = $this->champ;
    
    if (!empty($teams)) {
    
?>


					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-align-justify"></i><span class="break"></span>Tabela de posicoes</h2>
							
						</div>
						<div class="box-content">
							<table class="table">
								  <thead>
									  <tr>
                                                                            <th>Pos</th>
                                                                            <th>Time</th>
                                                                            <th>P</th>
                                                                            <th>J</th>
										                                  
									  </tr>
								  </thead>   
								  <tbody>
                                                                      
                                                                   <?php   
                                                                   
                                                                        for ($i = 0; $i < count($teams); $i = $i + 1) {
                                                                   
                                                                            $torneo = "";
                                                                            if ($i <= 2) {
                                                                                $torneo = "badge badge-success";
                                                                            }
                                                                            if ($i > 2 && $i <= 5) {
                                                                                $torneo = "badge badge-info";
                                                                            }
                                                                            
                                                                            if ($i > 15) {
                                                                                $torneo = "badge badge-important";
                                                                            }
                                                                            
                                                                            echo '<tr>
                                                                                    <td id="tm_id'.$i.'"><span class="'.$torneo.'">'.($i+1).'</td>
                                                                                    <td id="tm_name'.$i.'">'.Helpers_Html::getTeamLinkLeft($this->baseUrl(), $teams[$i]['tm_id'], $teams[$i]['tm_name'], $config->host.$teams[$i]['tm_logo'], $champ).'</td>
                                                                                    <td id="tm_points'.$i.'">'.$teams[$i]['tm_points'].'</td>
                                                                                    <td id="tm_played'.$i.'">'.$teams[$i]['tm_played'].'</td>
                                                                                                                         
                                                                            </tr>';
                                                                        
                                                                        }
                                                                        
                                                                    ?>    
                                                                                                          
								  </tbody>
							 </table>  
							 <div class="pagination pagination-centered">
							  <ul class="pagination" id="ul_positions">

                                                                
                                                                
							  </ul>
							</div>     
						</div>
					</div>
<?php

    };

?>