<?php

    $config = new Zend_Config_Ini("config.ini");

    $matchs = $this->jogos;
    $team = $this->nome_team;
    
//    print_r($team);
        
    $translate = Zend_Registry::get('translate');

    $box = new Helpers_Box();
    $box->matches = $matchs;
    $box->base = $this->baseUrl();
    $box->disabled_input = true;
    $box->mas_info = false;
    $box->palpites_goal = false;
    $box->show_final_result = true;
    $box->show_solo_nopalpitados = true;
    $box->show_solo_palpitados = true;
    $box->show_titulo_rodada = true;
    $box->tamanho_box = "col-lg-3 col-sm-6 col-xs-6 col-xxs-12 col-xxs-6";
    $box->id_result_input1 = "result1p_";
    $box->id_result_input2 = "result2p_";
    $box->id_box = "fila_";
    $box->id_html_team = "teamp_";
    $box->titulo_bigbox = "Jogos de ".$team;
    echo $box->big_box();