<?php

    $config = new Zend_Config_Ini("config.ini");

    $matchs = $this->jogos;
    $team = $this->nome_team;
    
//    print_r($team);
        
    $translate = Zend_Registry::get('translate');
?>


<div class="row">
        
    <div class="col-lg-8">
    
                <div class="box">
                        <div class="box-header">
                           
                            
                            
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span><?php echo $translate->_("jogos.do.time").": ".$team; ?></h2>
                                <div class="box-icon">

                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table" id="tb_palpites" >
                                          <thead>
                                                  <tr>
                                                    <th></th>
                                                    <th style="width:2%"></th>
                                                    <th></th>
                                                    <th></th>
                                                    <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              echo '<input type="hidden" value="'.count($matchs).'" name="count_palpites" id="count_palpites">';
                                              for ($i = 0; $i < count($matchs); $i = $i + 1) {  
                                                    $matchs[$i]['mt_date'] = Helpers_Data::day($matchs[$i]['mt_date']);
                                                    if (!$matchs[$i]['mt_played']) {
                                                        
                                                    }
                                                    if (($i == 0) || ($i > 0 && strcmp($matchs[$i]['mt_date'],$matchs[$i-1]['mt_date']) != 0)) { 
                                                        echo '
                                                            <tr>
                                                                <td></td>
                                                                <td></td>
                                                                <td style="text-align:center"><b>'.$translate->_("rodada").": ".$matchs[$i]['mt_round'].'</b></td>
                                                                
                                                            </tr>                                                            
                                                            <tr>
                                                                <td></td>
                                                                <td></td>
                                                                <td style="text-align:center"><b>'.$matchs[$i]['mt_date'].'</b></td>
                                                                
                                                            </tr>';                                      
                                                    }
                                                    echo '
                                                        <tr id="tr_'.$i.'">
                                                            <td style="text-align:right">'.Helpers_Html::getTeamLinkRight($this->baseUrl(), $matchs[$i]['tm1_id'], $matchs[$i]['t1nome'], $config->host.$matchs[$i]['tm1_logo'], $matchs[$i]['mt_idchampionship']).'</td>
                                                            <td></td>
                                                            <td class="col-sm-3 col-xs-3">
                                                                <div class="row">
                                                                    <div class="col-xs-6 col-sm-6 col-lg-6">
                                                                        <input disabled class="form-control" value="'.$matchs[$i]['mt_goal1'].'" type="text">
                                                                    </div>
                                                                    <div class="col-xs-6 col-sm-6 col-lg-6">
                                                                        <input disabled class="form-control" value="'.$matchs[$i]['mt_goal2'].'" type="text">
                                                                    </div>
                                                                </div>
                                                            </td>
                                                            <td style="text-align:left">'.Helpers_Html::getTeamLinkLeft($this->baseUrl(), $matchs[$i]['tm2_id'], $matchs[$i]['t2nome'], $config->host.$matchs[$i]['tm2_logo'], $matchs[$i]['mt_idchampionship']).'</td>
                                                            <td></td>                                      
                                                        </tr>';
                                                    }
                                               
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                               
                            <div class="form-action">
                                <!--<a href="javascript:void(0)" id="btnAceitarPalpites" class="btn btn-success">Aceitar Palpites</a>--> 
                            </div>
                        </div>
                </div>

    </div>
</div>
    

