<?php

    $config = new Zend_Config_Ini("config.ini");

        $matchs = $this->jogos;
        $team = $this->team;
        
?>


<div class="row">
        
    <div class="col-lg-8">
    
                <div class="box">
                        <div class="box-header">
                           
                            
                            
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Jogos</h2>
                                <div class="box-icon">

                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table" id="tb_palpites" >
                                          <thead>
                                                  <tr>
                                                    <th></th>
                                                    <th style="width:2%"></th>
                                                    <th></th>
                                                    <th></th>
                                                    <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              echo '<input type="hidden" value="'.count($matchs).'" name="count_palpites" id="count_palpites">';
                                              for ($i = 0; $i < count($matchs); $i = $i + 1) {  
                                                    $date = date("H:i",strtotime($matchs[$i]['mt_date']))."hs. ".date("d-m-y",strtotime($matchs[$i]['mt_date']) );
                                                    $matchs[$i]['mt_date'] = $date;
                                                    if (($i == 0) || ($i > 0 && strcmp($matchs[$i]['mt_date'],$matchs[$i-1]['mt_date']) != 0)) { 
                                                        echo '
                                                            <tr>
                                                                <td></td>
                                                                <td></td>
                                                                <td style="text-align:center"><b>Rodada '.$matchs[$i]['mt_round'].'</b></td>
                                                                
                                                            </tr>                                                            
                                                            <tr>
                                                                <td></td>
                                                                <td></td>
                                                                <td style="text-align:center"><b>'.Helpers_Data::day($date).'</b></td>
                                                                
                                                            </tr>';                                      
                                                    }
                                                    echo '
                                                        <tr id="tr_'.$i.'">
                                                            <td style="text-align:right">'.$matchs[$i]['t1nome'].'<img width="28px;" height="21px;" src="'.$config->host.$matchs[$i]['tm1_logo'].'" /></td>
                                                            <td></td>
                                                            <td class="col-sm-3 col-xs-3">
                                                                <div class="row">
                                                                    <div class="col-xs-6 col-sm-6 col-lg-6">
                                                                        <input disabled class="form-control" value="'.$matchs[$i]['mt_goal1'].'" type="text" placeholder="0">
                                                                    </div>
                                                                    <div class="col-xs-6 col-sm-6 col-lg-6">
                                                                        <input disabled class="form-control" value="'.$matchs[$i]['mt_goal2'].'" type="text" placeholder="0">
                                                                    </div>
                                                                </div>
                                                            </td>
                                                            <td style="text-align:left"><img width="28px;" height="21px;" src="'.$config->host.$matchs[$i]['tm2_logo'].'" />'.$matchs[$i]['t2nome'].'</td>
                                                            <td></td>                                      
                                                        </tr>';
                                                    }
                                               
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                               
                            <div class="form-action">
                                <!--<a href="javascript:void(0)" id="btnAceitarPalpites" class="btn btn-success">Aceitar Palpites</a>--> 
                            </div>
                        </div>
                </div>

    </div>
</div>
    

