<?php

$champs = $this->champs;


?>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-content">
                <form id="frChamp_palpites" action="<?php echo $this->baseUrl()."/admin/time"; ?>" method="post">	
                    <div class="form-group">                                      
                        <div class="controls">
                              <div class="input-group date col-sm-12">
                                      <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                      <div class="controls">
                                      <input type="hidden" value="1" name="rodada" />
                                      <select id="championship" name="championship" class="form-control">
                                      <?php   
                                          if (empty($pencas)) {
                                              echo '<option value="Vazio"></option>';    
                                          }

                                          for ($i = 0; $i < count($champs); $i = $i + 1) {
                                              $selected = "";
                                              if (!empty($champ) && $champs[$i]['ch_id'] == $champ) {
                                                  $selected = "selected";    
                                              }
                                              echo '<option '.$selected.' value="'.$champs[$i]['ch_id'].'">'.$champs[$i]['ch_nome'].'</option>';
                                          }                                                        
                                      ?>
                                      </select></div>
                              </div>	
                        </div>    
                    </div>  
                    <div class="form-group">                                        
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="time" name="time" class="form-control" placeholder="Time">
                              </div>                          
                        </div>
                    </div>
                    <div class="form-group">                                        
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                                <input type="text" id="grupo" name="grupo" class="form-control" placeholder="Grupo">
                              </div>                          
                        </div>
                    </div>                    
                    <div class="form-group">                                        
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="logo" name="logo" class="form-control" placeholder="Logo">
                              </div>                              
                        </div>
                    </div>                    
                    <div class="form-actions">
                        <button type="button" id="salvar_team" class="btn btn-primary">Salvar</button>
                      </div>
                </form>   
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    
    $(function() {
       $("#salvar_team").bind("click", function() {
          var time = $("#time").val();
          var logo = $("#logo").val();
          var champ = $("#championship").val();
          var grupo = $("#grupo").val();
          
          $.post("time/salvartime", {time : time, logo : logo, championship : champ, grupo : grupo}, function(response) {
             console.log(response); 
             alert(response);
          });
          
       }); 
    });
    

</script>