<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-content">
                <form id="frChamp_palpites" action="<?php echo $this->baseUrl()."/admin/campeonato"; ?>" method="post">	
                        
                    <div class="form-group">                                        
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="campeonato" class="form-control" placeholder="Campeonato">
                              </div>                                              
                        </div>
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="sec1inicio" class="form-control" placeholder="Sector 1 Inicio">
                              </div>                                              
                        </div>
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="sec1fin" class="form-control" placeholder="Sector 1 Fin">
                              </div>                                              
                        </div>      
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="sec1descripcion" class="form-control" placeholder="Sector 1 Descripcion">
                              </div>                                              
                        </div>                              
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="sec2inicio" class="form-control" placeholder="Sector 2 Inicio">
                              </div>                                              
                        </div>                          
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="sec1fin" class="form-control" placeholder="Sector 2 Fin">
                              </div>                                              
                        </div>          
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="sec2descripcion" class="form-control" placeholder="Sector 2 Descripcion">
                              </div>                                              
                        </div>                          
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="campeonato" class="form-control" placeholder="Sector 3 Inicio">
                              </div>                                              
                        </div>                              
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="campeonato" class="form-control" placeholder="Sector 3 Fin">
                              </div>                                              
                        </div>             
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="campeonato" class="form-control" placeholder="Sector 3 Descripcion">
                              </div>                                              
                        </div>                          
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Salvar Campeonato</button>
                      </div>
                </form>   
            </div>
        </div>
    </div>
</div>