<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-content">
                <form id="frChamp_palpites" action="<?php echo $this->baseUrl()."/admin/campeonato"; ?>" method="post">	
                        
                    <div class="form-group">                                        
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="campeonato" name="campeonato" class="form-control" placeholder="Campeonato">
                              </div>                                              
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Salvar Campeonato</button>
                      </div>
                </form>   
            </div>
        </div>
    </div>
</div>