<?php 

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];

    $palpites = $this->palpites;
?>

<div class="col-xs-5 col-sm-12">
    <ul class="profile-details">
            <li>
                    <div><i class="fa <?php echo $info_penca['pn_icone']; ?>"></i></div>
                    <?php echo $info_penca['pn_name']; ?>
            </li>
            <li>
                    <div><i class="fa fa-dribbble"></i></div>
                    <?php echo $info_penca['ch_nome']; ?>
            </li>
    </ul>

    <ul class="profile-details">
            <li>
                <div><i class="fa fa-user"></i></div>
                <?php echo $info_penca['us_username']; ?>
            </li>
            <li>
                <div><i class="fa fa-unlock"></i></div>
                <?php
                    if (empty($info_penca['pn_justfriends'])) {
                        echo '<span class="label label-success">Aberto</span>';
                    } else {
                        echo '<span class="label label-important">Fechado</span>';
                    }
                ?>
            </li>
            <li>
                <div><i class="fa fa-caret-right"></i></div>
                comecou
            </li>
            <li>
                <?php 
                if (!($info_penca['pn_justfriends'])) {
//                    print_r($this->is_inscripto);
//                    die("insc");
                    if (empty($this->is_iscripto)) {
                        echo '<form action="inscribir" method="post">'
                        .'<input type="hidden" value="'.$this->penca.'" name="penca">'
                        .'<input type="hidden" value="'.$this->championship.'" name="championship">'        
                        . '<button class="btn btn-lg btn-success"><b>PARTICIPAR</b></button>'
                        . '</form>';
                    } else  {
                        echo '<form action="sairpenca" method="post">'
                        .'<input type="hidden" value="'.$this->penca.'" name="penca">'
                        .'<input type="hidden" value="'.$this->championship.'" name="championship">'        
                        . '<button class="btn btn-lg btn-danger"><b>SAIR</b></button>'
                        . '</form>';                        
                    }
                }
                ?>
            </li>
    </ul>
</div>	