<?php 

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];

?>

<div class="col-xs-5 col-sm-12">
    <h3>Informacao Geral</h3>

    <ul class="profile-details">
            <li>
                    <div><i class="fa fa-briefcase"></i> Nome</div>
                    <?php echo $info_penca['pn_name']; ?>
            </li>
            <li>
                    <div><i class="fa fa-building-o"></i> Campeonato</div>
                    <?php echo $info_penca['ch_nome']; ?>
            </li>
    </ul>		

    <h3>Usuarios</h3>

    <ul class="profile-details">
            <li>
                <div><i class="fa fa-phone"></i> Administrador</div>
                <?php echo $info_penca['us_username']; ?>
            </li>
            <li>
                <div><i class="fa fa-tablet"></i>Disponibilidade</div>
                <?php
                    if (empty($info_penca['pn_justfriends'])) {
                        echo '<span class="label label-success">Aberto</span>';
                    } else {
                        echo '<span class="label label-important">Fechado</span>';
                    }
                ?>
            </li>
            <li>
                <div><i class="fa fa-envelope"></i>Status</div>
                comecou
            </li>
    </ul>
</div>	