<?php 

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];
    
    $palpites = $this->palpites;

?>
<div class="tab-pane active" id="palpites">
                                                    
    <div class="row">
        <form action="aceitarpalpites" method="post" id="formPalpites">
        <div class="col-lg-10">
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Rodada: <?php echo $palpites[0]['rs_round']; ?></h2>
                                <div class="box-icon">
<!--                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>-->
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table">
                                          <thead>
                                                  <tr>
                                                          <th width="15%"></th>
                                                          <th></th>
                                                          <th width="15%"></th>
                                                          <th></th> 
                                                          <th width="15%"></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                              echo '<input type="hidden" value="'.count($palpites).'" name="count_palpites">';
                                                for ($i = 0; $i < count($palpites); $i = $i + 1) {
                                                    echo '<input type="hidden" name="rs_'.$i.'" value="'.$palpites[$i]['rs_id'].'" />';
                                                    echo '
                                                        <tr>
                                                            <td></td>
                                                            <td>
                                                           '.date("H:i",strtotime($palpites[$i]['mt_date']))."hs. ".date("d-m-y",strtotime($palpites[$i]['mt_date']) ).'
                                                            </td>                                      
                                                        </tr>
                                                            <tr>
                                                            <td width="15%">
                                                                <div class="input-group col-sm-7">
                                                                    <input class="form-control"name="result1_'.$i.'" value="'.$palpites[$i]['rs_res1'].'"  type="text" placeholder="0">
                                                                </div>
                                                            </td>
                                                            <td>'.$palpites[$i]['t1nome'].'</td>
                                                            <td></td>
                                                            <td>'.$palpites[$i]['t2nome'].'</td>
                                                            <td width="15%">     
                                                                <div class="input-group col-sm-7">		
                                                                    <input class="form-control" value="'.$palpites[$i]['rs_res2'].'" name="result2_'.$i.'" type="text" placeholder="0">
                                                                </div>
                                                            </td>
                                                            </td>                                      
                                                        </tr>';
                                                }
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                                 <div class="pagination pagination-centered">
                                  <ul class="pagination">
                                      
                                      <li><a href="table.html#">Prev</a></li>
                                        <li class="active">
                                          <a href="table.html#">1</a>
                                        </li>
                                        <li><a href="table.html#">2</a></li>
                                        <li><a href="table.html#">3</a></li>
                                        <li><a href="table.html#">4</a></li>
                                        <li><a href="table.html#">Next</a></li>
                                  </ul>
                                     
                                     
                                     
                                </div> 
                            <div class="form-action">
                                <a href="javascript:void(0)" id="btnAceitarPalpites" class="btn btn-success">Aceitar Palpites</a> 
                            </div>
                        </div>
                </div>
        </div>
        </form>
    </div>

</div>

<script type="text/javascript">
    $(function() {
        $('#btnAceitarPalpites').bind('click', function() {
            $.post("aceitarpalpites", $('#formPalpites').serialize(), function(response) {
               console.log(response); 
            });
        })
    });
    
</script>