<?php 

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];
    
    $palpites = $this->palpites;

?>
<div class="tab-pane active" id="palpites">
                                                    
    <div class="row">
        
        <div class="col-lg-10">
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Simple Table</h2>
                                <div class="box-icon">
                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table">
                                          <thead>
                                                  <tr>
                                                          <th></th>
                                                          <th></th>
                                                          <th>Data</th>
                                                          <th></th> 
                                                          <th></th> 
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                              
                                              <?php
                                                for ($i = 0; $i < count($palpites); $i = $i + 1) {
                                                    echo '<tr>
                                                            <td>'.$palpites[$i]['rs_res1'].'</td>
                                                            <td>'.$palpites[$i]['mt_idteam1'].'</td>
                                                            <td>'.$palpites[$i]['mt_date'].'</td>
                                                            <td>'.$palpites[$i]['mt_idteam2'].'</td>
                                                            <td>'.$palpites[$i]['rs_res2'].'</td>                                      
                                                        </tr>';
                                                }
                                              
                                              ?>
                                              
                                                                           
                                          </tbody>
                                 </table>  
                                 <div class="pagination pagination-centered">
                                  <ul class="pagination">
                                        <li><a href="table.html#">Prev</a></li>
                                        <li class="active">
                                          <a href="table.html#">1</a>
                                        </li>
                                        <li><a href="table.html#">2</a></li>
                                        <li><a href="table.html#">3</a></li>
                                        <li><a href="table.html#">4</a></li>
                                        <li><a href="table.html#">Next</a></li>
                                  </ul>
                                </div>     
                        </div>
                </div>
        </div>
        
    </div>

</div>