<?php 

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];

?>

<div class="row">
    
    
    
</div>
					

<script type="text/javascript">
   $(function() {
       
       $('#tbParticipantes').bind('click', function() {
            alert($('#idpenca').attr("value"));   
//            $.post('usuariospenca',{penca: curso}, function(response) {
//               
//           });
       });
   });
    
</script>