<?php 

    $info_penca = $this->info_penca;
    $info_penca = $info_penca[0];

?>

<div class="row">
    
    
    
</div>
					

<script type="text/javascript">
   $(function() {
       
       $('#tbParticipantes').bind('click', function() {
            var penca = $('#idpenca').attr("value");  
            $.post('usuariospenca',{penca: penca}, function(response) {
                console.log(response);
            });
       });
   });
    
</script>