<?php

    $i = $this->info_penca;
    $info_penca = $i[0];
    
    $teams = $this->teams;
    
    $p = $this->participantes;
    $participantes = $p[0];
    
    $round = $this->rodada;
?>

	<div class="tab-pane active" id="photos">
                                                    
                             <!-- swewrewr -->                       
                                        <div class="row">
				<div class="col-lg-6">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-align-justify"></i><span class="break"></span>Tabela de posicoes</h2>
							
						</div>
						<div class="box-content">
							<table class="table">
								  <thead>
									  <tr>
                                                                            <th>Pos</th>
                                                                            <th>Time</th>
                                                                            <th>P</th>
                                                                            <th>J</th>
										                                  
									  </tr>
								  </thead>   
								  <tbody>
                                                                      
                                                                   <?php   
                                                                   
                                                                        for ($i = 0; $i < count($teams); $i = $i + 1) {
                                                                   
                                                                            echo '<tr>
                                                                                    <td>'.($i+1).'</td>
                                                                                    <td>'.$teams[$i]['tm_name'].'</td>
                                                                                    <td>'.$teams[$i]['tm_points'].'</td>
                                                                                    <td>'.$teams[$i]['tm_played'].'</td>
                                                                                                                         
                                                                            </tr>';
                                                                        
                                                                        }
                                                                        
                                                                    ?>    
                                                                                                          
								  </tbody>
							 </table>  
							 <div class="pagination pagination-centered">
							  <ul class="pagination">
								<li><a href="table.html#">Prev</a></li>
								<li class="active">
								  <a href="table.html#">1</a>
								</li>
								<li><a href="table.html#">2</a></li>
								<li><a href="table.html#">3</a></li>
								<li><a href="table.html#">4</a></li>
								<li><a href="table.html#">Next</a></li>
							  </ul>
							</div>     
						</div>
					</div>
				</div><!--/col-->
				
				<!--/col-->
                                
                                
                                
                                <!-- PARTICIPANTES   -->
                                
                                <div class="col-lg-5 col-sm-6 col-xs-6 col-xxs-12">
					<div class="smallstat box">
                                                <?php
                                                    if ($info_penca['pn_justfriends'] == 1) {
                                                        echo '<i class="fa fa-flag red"></i>';                                                        
                                                    } else {
                                                        echo '<i class="fa fa-flag green"></i>';
                                                    }
                                                ?>
						
						<span class="title">Status</span>
						<span class="value">
                                                <?php
                                                    if ($info_penca['pn_justfriends'] == 1) { 
                                                        echo 'Fechado';
                                                    } else {
                                                        echo 'Aberto';
                                                    }
                                                
                                                ?>
                                                </span>
						<a href="" class="more">
							
						</a>
					</div>
				</div>
                                
                                <div class="col-lg-5 col-sm-6 col-xs-6 col-xxs-12">
					<div class="smallstat box">
						<i class="fa fa-user blue"></i>
						<span class="title">Participantes</span>
						<span class="value"><?php echo $participantes['participantes']; ?></span>
						<a href="" class="more">
							
						</a>
					</div>
				</div>
                                
                                <div class="col-lg-5 col-sm-6 col-xs-6 col-xxs-12">
					<div class="smallstat box">
						<i class="fa fa-dollar green"></i>
						<span class="title">Acumulado</span>
						<span class="value">R$ <?php echo $info_penca['pn_valueaccumulated']; ?></span>
						<a href="" class="more">
							
						</a>
					</div>
				</div>                                
                                
			</div>     
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                          <!-- dfsdgsgfsf -->                          
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    <div class="row">	
				<div class="col-lg-12">
					<div class="box">
						<div class="box-header">
							<h2><i class="fa fa-align-justify"></i><span class="break"></span>Rodada <?php echo $round[0]['mt_round']; ?></h2>
							<div class="box-icon">
								<a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
								<a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
								<a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
							</div>
						</div>
						<div class="box-content">
							<table class="table table-bordered table-striped table-condensed">
								  <thead>
									  <tr>
                                                                                  
										  <th></th>
										  <th>Data</th>
										  <th></th>
										                                         
									  </tr>
								  </thead>   
								  <tbody>
                                                                      
                                                                      <?php
                                                                        for ($i = 0; $i < count($round); $i = $i + 1) {
                                                                            echo '<tr>                                                                                    
                                                                                    <td>'.$round[$i]['t1nome'].'</td>
                                                                                    <td>'.$round[$i]['mt_date'].'</td>
                                                                                    <td>'.$round[$i]['t2nome'].'</td>                                       
                                                                                </tr>';   
                                                                        }
                                                                      
                                                                      
                                                                      ?>
                            
								  </tbody>
							 </table>  
							 <div class="pagination pagination-centered">
							  <ul class="pagination">
								<li><a href="table.html#">Prev</a></li>
								<li class="active">
								  <a href="table.html#">1</a>
								</li>
								<li><a href="table.html#">2</a></li>
								<li><a href="table.html#">3</a></li>
								<li><a href="table.html#">4</a></li>
								<li><a href="table.html#">Next</a></li>
							  </ul>
							</div>     
						</div>
					</div>
				</div><!--/col-->
			</div>  
							
					
					  	</div>