<?php

$champs = $this->championships;

$matchs = $this->matchs;

?>


<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-content">
                <form id="frChamp_palpites" action="<?php echo $this->baseUrl('/admin/resultados'); ?>" method="post">	
                    <div class="form-group">                                      
                                      <div class="controls">
                                            <div class="input-group date col-sm-4">
                                                    <span class="input-group-addon"><i class="fa  fa-search"></i></span>
                                                    <div class="controls">
                                                    <input type="hidden" value="1" name="rodada" />
                                                    <select id="championship" name="champ" class="form-control">
                                                    <?php   
                                                        if (empty($pencas)) {
                                                            echo '<option value="Vazio"></option>';    
                                                        }
                                                        
                                                        for ($i = 0; $i < count($champs); $i = $i + 1) {
                                                            $selected = "";
                                                            if (!empty($champ) && $champs[$i]['ch_id'] == $champ) {
                                                                $selected = "selected";    
                                                            }
                                                            echo '<option '.$selected.' value="'.$champs[$i]['ch_id'].'">'.$champs[$i]['ch_nome'].'</option>';
                                                        }                                                        
                                                    ?>
                                                    </select></div>
                                            </div>	
                                      </div>
                                    </div>    
                    <div class="form-group">                                        
                        <div class="controls">
                              <div class="input-group col-sm-4">
                                <span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
                                <input type="text" id="ronda" name="ronda" class="form-control" placeholder="N° Ronda">
                              </div>                                              
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Cargar Partidos</button>
                      </div>
                </form>   
            </div>
        </div>
    </div>
</div>


<?php

    if (!empty($matchs)) {
        
?>        
    <div class="row">
        <div class="col-lg-12">
                <div class="box">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Simple Table</h2>
                                <div class="box-icon">
                                        <a href="table.html#" class="btn-setting"><i class="fa fa-wrench"></i></a>
                                        <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                                        <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
                                </div>
                        </div>
                        <div class="box-content">
                                <table class="table">
                                          <thead>
                                                  <tr>
                                                          <th>Fecha</th>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th>
                                                          <th></th>
                                                          <th>Opciones</th>                                          
                                                          <th></th>
                                                  </tr>
                                          </thead>   
                                          <tbody>
                                          
                                            <?php      
                                                for ($i = 0; $i < count($matchs); $i = $i + 1) {                                                    
                                                    $jogado = false;
                                                    $disabled = "";
                                                    if ($matchs[$i]['mt_played']) {
                                                        //$jogado = true;
                                                        $disabled="disabled";
                                                    }
                                                    echo '<input type="hidden" id="idteam1_'.$matchs[$i]['mt_id'].'" value="'.$matchs[$i]['mt_idteam1'].'">';
                                                    echo '<input type="hidden" id="idteam2_'.$matchs[$i]['mt_id'].'" value="'.$matchs[$i]['mt_idteam2'].'">';
                                                    echo '<tr>
                                                            <td>'.$matchs[$i]['mt_date'].'</td>
                                                            <td><input id="res1_'.$matchs[$i]['mt_id'].'" value="'.$matchs[$i]['mt_goal1'].'" '.$disabled.' size="3" type="text"></td>
                                                            <td>'.$matchs[$i]['t1nome'].'</td>
                                                            <td><input id="res2_'.$matchs[$i]['mt_id'].'" value="'.$matchs[$i]['mt_goal2'].'" '.$disabled.' size="3" type="text"></td>        
                                                            <td>'.$matchs[$i]['t2nome'].'</td>
                                                            <td>';
                                                                if (!$jogado) {
                                                                    
                                                                    echo '<a class="btn btn-success btnslvr" href="javascript:void(0)" match="'.$matchs[$i]['mt_id'].'" id="btnSalvarRes">
                                                                        <i class="fa fa-check "></i>                                            
                                                                    </a>';                                                                    
                                                                }
                                                            echo '</td> 
                                                            <td><span id="rs_success_'.$matchs[$i]['mt_id'].'">&nbsp&nbsp</span></td>
                                                    </tr>';
                                                }        
                                                        
                                            ?>            
                                          </tbody>
                                 </table>  

                        </div>
                </div>
        </div><!--/col-->

        <!--/col-->
</div>

<?php

    }

?>

<script type="text/javascript">
    $(function() { 
        $(".btnslvr").bind('click', function() {
           var match = $(this).attr("match"); 
           var res1 = $("#res1_"+match).val();
           var res2 = $("#res2_"+match).val();
           var team1 = $("#idteam1_"+match).val();
           var team2 = $("#idteam2_"+match).val();
           
           $.post("resultados/setresultado", {team1: team1, team2: team2, match : match, res1 : res1, res2 : res2}, function(response) {
                console.log(response);
                if (response == 200) {
                    $("#rs_success_"+match).html('<span class="label label-success">Complete</span>');
                }
                //<span class="label label-success">Complete</span>
           });
        });
    })
</script>