<?php




 $t = Zend_Registry::get('translate');   

?>

<center><h1><?php echo $t->_("adicionar.saldo"); ?></h1></center>

<h2>Para adicionar saldo a sua conta e realizar palpites, clique em alguma plano abaixo para realizar o pagamento, toda transação será realizada pelo sistema do 
    PagSeguro, o site Craque de Bola não ira solicitar nenhuma informação contendo dados de cartões, confira nossos planos:</h2>

<div class="row">
    <div class="col-sm-8 col-lg-3 col-xs-12">

        <div class="smallchart blue box">

                <div class="title" style="background-color:gray !important"><?php echo $t->_("plano.basico"); ?></div>



                <div class="title" style="background-color:gray !important"><?php echo $t->_("custo"); ?>: <?php echo $t->_("moeda"); ?> 10.80</div>
                <div class="title" style="background-color:gray !important"><?php echo $t->_("credito"); ?>: <?php echo $t->_("moeda"); ?> 10.00</div>                

                
                <div class="title" style="background-color:gray !important"><a href="<?php echo $this->baseUrl();?>/caixa/plano?p=1" class="btn btn-success"><?php echo $t->_("selecionar"); ?></a></div>                
        </div>

    </div>
    
    <div class="col-sm-8 col-lg-3 col-xs-12">

        <div class="smallchart blue box">

                <div class="title" style="background-color:gray !important"><?php echo $t->_("plano.standar"); ?></div>



                <div class="title" style="background-color:gray !important"><?php echo $t->_("custo"); ?>: <?php echo $t->_("moeda"); ?> 21.20</div>
                <div class="title" style="background-color:gray !important"><?php echo $t->_("credito"); ?>: <?php echo $t->_("moeda"); ?> 20.00</div>                

                
                <div class="title" style="background-color:gray !important"><a href="<?php echo $this->baseUrl();?>/caixa/plano?p=2" class="btn btn-success">Selecionar</a></div>                

        </div>

    </div>
    
    <div class="col-sm-8 col-lg-3 col-xs-12">

        <div class="smallchart blue box">

<div class="title" style="background-color:gray !important"><?php echo $t->_("plano.premium"); ?></div>



                <div class="title" style="background-color:gray !important"><?php echo $t->_("custo"); ?>: <?php echo $t->_("moeda"); ?> 52.40</div>
                <div class="title" style="background-color:gray !important"><?php echo $t->_("credito"); ?>: <?php echo $t->_("moeda"); ?> 50.00</div>    
                <div class="title" style="background-color:gray !important">1 <?php echo $t->_("palpite.de.brinde"); ?></div>    

                
                <div class="title" style="background-color:gray !important"><a href="<?php echo $this->baseUrl();?>/caixa/plano?p=3" class="btn btn-success">Selecionar</a></div>                

        </div>

    </div>
    
    <div class="col-sm-8 col-lg-3 col-xs-12">

        <div class="smallchart blue box">

<div class="title" style="background-color:gray !important"><?php echo $t->_("plano.profissional"); ?></div>



                <div class="title" style="background-color:gray !important"><?php echo $t->_("custo"); ?>: <?php echo $t->_("moeda"); ?> 104.40</div>
                <div class="title" style="background-color:gray !important"><?php echo $t->_("credito"); ?>: <?php echo $t->_("moeda"); ?> 100.00</div>    
                <div class="title" style="background-color:gray !important">3 <?php echo $t->_("palpites.de.brinde"); ?></div>  
                
                <div class="title" style="background-color:gray !important"><a href="<?php echo $this->baseUrl();?>/caixa/plano?p=4" class="btn btn-success">Selecionar</a></div>                

        </div>

    </div>    
</div>