
<?php




    $ts = $this->transactions;
    $ts_credito = $this->tr_credito;
    $rs = $this->ranking;
//    print_r($rs);
    
    $config = new Zend_Config_Ini("config.ini");
    
    $cs = $this->champs;
    $rds = array() ;
    
    
    $champ = "";
    $round_filtro_palpites = "";
    if (!empty($this->rondas)) {
        $rds = $this->rondas;
        $champ = $this->champ;
        $round_filtro_palpites = $this->round;
    }

    
//    print_r($ts);
    
    
//    print_r("RODADA ".$round_filtro_palpites);
//    print_r($rds);
    ?>

<div class="row">
        
<div class="col-lg-4">
<div class="box">
    

    
                    <form id="frmCaixaCamp" action="transacoes" method="post">
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Palpites</h2>
                                <div class="box-icon">
                                    
                                </div>
                        </div>
                        <div class="box-content">
                            
                            <div class="row">
                            
                            <div style="" id="rs_dados_111" class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12 col-xxs-12">
                                
                                
                                <div class="form-inline" id="frFiltroTransacao" style="text-align:left !important;margin-bottom:15px">
                                        <div class="form-group">                                      
                                            <div class="controls">
                                                <div class="input-group">
                                                  <div class="controls">
                                                    
                                                        <select id="campeonato" name="campeonato" class="form-control">

                                                        <?php 
                                                            echo '<option value="Vazio">Vazio</option>';       
                                                            for ($i = 0; $i < count($cs); $i++) {
                                                                $selected = "";
                                                                
                                                                if ($cs[$i]['ch_id'] == $champ) {
                                                                    $selected = "selected";
                                                                }
                                                                echo '<option '.$selected.' value="'.$cs[$i]['ch_id'].'">'.$cs[$i]['ch_nome'].'</option>';       
                                                            }                                                    

                                                        ?>

                                                        </select>

                                                  </div>
                                                </div>                                        
                                            </div>    
                                        </div>
                                        
                                        <div class="form-group">                                      
                                            <div class="controls">
                                                <div class="input-group">
                                                  <div class="controls">
                                                        <select id="rodada" name="rodada" class="form-control">
                                                            
                                                            <option value="Vazio">Vazio</option>
                                                            <?php
                                                            
                                                                
                                                            
                                                                for ($i = 0; $i < count($rds); $i = $i + 1 ) {

                                                                    $selected = "";
                                                                    if ($rds[$i]['rd_id'] == $round_filtro_palpites) {
                                                                        $selected = "selected";
                                                                    }
                                                                    echo '<option '.$selected.' value="'.$rds[$i]['rd_id'].'">'.$rds[$i]['rd_round'].'</option>';
                                                                }
                                                            
                                                            ?>
                                                            
                                                           
                                                           
                                                         </select>  
                                                  </div>
                                                </div>                                        
                                            </div>    
                                        </div>
                                        </div>
                                
                                
                                
                        <div class="smallstat box">
                            <table>
                                <?php
                                        
                                    $ch_nome = "";
                                    $round = "";
                                    $total_rodada = 0;
                                    for ($i = 0; $i < count($ts); $i++) {
                                        if (strcmp($ch_nome, $ts[$i]['ch_nome']) != 0) {
                                            echo '<tr><td>'.$ts[$i]['ch_nome'].'</td></tr>';
                                            $ch_nome = $ts[$i]['ch_nome'];
                                        }
                                        if (strcmp($round, $ts[$i]['mt_idround']) != 0) {
                                            if ($i != 0) {
                                                echo '<tr><td width="60%" style="text-align:center">Total</td><td width="20%" style="text-align:left">'.number_format((float)(-1)*$total_rodada, 2, ".","").'</td><td width="20%"></td></tr>';
                                                echo '<td width="60%" style="text-align:center"></td><td width="20%" style="text-align:left">&nbsp;</td><td width="20%"></td>';
                                            }                                            
                                            echo '<tr><td>Rodada '.$ts[$i]['mt_idround'].'</td></tr>';
                                            $round = $ts[$i]['mt_idround'];  
                                            $total_rodada = 0;
                                        } 
                                        $total_rodada = $total_rodada + $ts[$i]['tr_valortransaccion'];
                                        
                                        $color = "";
                                        if ($ts[$i]['tr_valortransaccion'] > 0) {
                                            $color = "; color : red";
                                            
                                        } else { 
                                            $ts[$i]['tr_valortransaccion'] = number_format((float)(-1)*$ts[$i]['tr_valortransaccion'],2,".","");
                                        }
                                        echo '<tr><td width="60%" style="text-align:center">'
                                        . '<img width="28px;" height="21px;" src="'.$config->host.$ts[$i]['tm1_logo'].'" />'
                                                . ' vs <img width="28px;" height="21px;" src="'.$config->host.$ts[$i]['tm2_logo'].'" /></td>'
                                        . '<td width="20%" style="text-align:left'.$color.'">'.$ts[$i]['tr_valortransaccion'].'</td>'
                                        . '<td width="20%" style="text-align:right">'.$ts[$i]['tr_res_us_cash'].'</td>'
                                       . '</tr>';
                                        
                                        
                                    }
                                    if (count($ts) > 0) {
                                        echo '<td width="60%" style="text-align:center">Total</td><td width="20%" style="text-align:left">'.number_format((float)(-1)*$total_rodada, 2, ".","").'</td><td width="20%"></td>';
                                    }
                                
                                
                                ?>
                            </table>
                                
                        </div>
                </div>                            
<!--                                <div>
                                    HOLA
                                </div>-->
                               
                            <div class="form-action">  
                                
                            </div>
                            </div>
                        </div>
                                            
                    </form>
                </div>
</div>
    
    
    
    
    
    
<div class="col-lg-4">
<div class="box">
                    <!--<form action="/penca/public/penca/processarpalpites" method="post" id="processarpalpites" >-->
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Creditos</h2>
                                <div class="box-icon">
                                    <span><h2 style="margin-right: 30px !important" id="ronda_total_palpitado"></h2></span>
                                </div>
                        </div>
                        <div class="box-content">
                            
                            <div class="row">
                            
                            <div style="" id="rs_dados_111" class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12 col-xxs-12">
                        <div class="smallstat box">
                            <table>
                                <?php
                                
                                    for ($i = 0; $i < count($ts_credito); $i++) {
                                        $date = "";
//                                        print_r($ts_credito);
                                        if (!empty($ts_credito[$i]['tr_date'])) {
                                            $date = Helpers_Data::formats($ts_credito[$i]['tr_date']);
                                        }
                                        $icone = "";
                                        if (isset($ts_credito[$i]['tr_tipo']) && strcmp($ts_credito[$i]['tr_motivo'],"JOGO") == 0) {
                                            $icone = 'globe';
                                        }
                                        if (isset($ts_credito[$i]['tr_tipo']) && strcmp($ts_credito[$i]['tr_motivo'],"CAMPEONATO") == 0) {
                                            $icone = 'trophy';
                                        }         
                                        if (isset($ts_credito[$i]['tr_tipo']) && strcmp($ts_credito[$i]['tr_motivo'],"RODADA") == 0) {
                                            $icone = 'star';
                                        }                                          
                                        echo '<tr>'
                                        . '<td width="5%" style="text-align:left"><div><i style="color:black !important; padding: 6px 0 !important; font-size: 10px !important; margin-right: 0px !important; width: 15px !important" class="fa fa-'.$icone.'"></i></div></td>'
                                        . '<td width="55%" style="text-align:left">'.$date.'</td>'
                                        . '<td width="20%" style="text-align:left">'.$ts_credito[$i]['tr_valortransaccion'].'</td>'
                                        . '<td width="20%" style="text-align:right">'.$ts_credito[$i]['tr_res_us_cash'].'</td>'      
                                       . '</tr>';
                                        
                                        
                                    }
                                
                                
                                
                                ?>
                            </table>
                                
                        </div>
                </div>                            
<!--                                <div>
                                    HOLA
                                </div>-->
                               
                            <div class="form-action">  
                                
                            </div>
                            </div>
                        </div>
                                            
                    <!--</form>-->
                </div>
</div>
    
    
    
    
    
    
    
<div class="col-lg-4">
<div class="box">
                    <!--<form action="/penca/public/penca/processarpalpites" method="post" id="processarpalpites" >-->
                        <div class="box-header">
                                <h2><i class="fa fa-align-justify"></i><span class="break"></span>Ranking</h2>
                                <div class="box-icon">
                                    
                                </div>
                        </div>
                        <div class="box-content">
                            
                            <div class="row">
                            
                            <div style="" id="rs_dados_111" class="col-lg-12 col-sm-12 col-xs-12 col-xxs-12 col-xxs-12">
                        <div class="smallstat box">
                            <table>
                                <?php
                                
                                    for ($i = 0; $i < count($rs); $i++) {
                                        echo '<tr><td width="10%" style="text-align:left">'.$rs[$i]['position'].'</td>'
                                                .'<td width="10%" style="text-align:left">'.$rs[$i]['points'].'</td>'
                                        . '<td width="20%" style="text-align:left">'.$rs[$i]['ch_nome'].'</td>'
                                       . '</tr>';
                                        
                                        
                                    }
                                
                                
                                
                                ?>
                            </table>
                                
                        </div>
                </div>                            
<!--                                <div>
                                    HOLA
                                </div>-->
                               
                            <div class="form-action">  
                                
                            </div>
                            </div>
                        </div>
                                            
                    <!--</form>-->
                </div>
</div>
    
    
    
    
    
    </div>



<script type="text/javascript">
    
    $("#campeonato").change(function() {
       $("#frmCaixaCamp").submit();
    });
        
    $("#rodada").change(function() {
       $("#frmCaixaCamp").submit();
    });
    
</script>    
    